export const SET_CONSUMABLES = 'SET_CONSUMABLES';
export const POST_UPDATE_CONSUMABLE_START = 'POST_UPDATE_CONSUMABLE_START';
export const POST_UPDATE_CONSUMABLE_END = 'POST_UPDATE_CONSUMABLE_END';
export const POST_UPDATE_CONSUMABLE_ERROR = 'POST_UPDATE_CONSUMABLE_ERROR';

export const UPDATE_CONSUMABLE_STATUS_START = 'UPDATE_CONSUMABLE_STATUS_START';
export const UPDATE_CONSUMABLE_STATUS_END = 'UPDATE_CONSUMABLE_STATUS_END';
export const UPDATE_CONSUMABLE_STATUS_ERROR = 'UPDATE_CONSUMABLE_STATUS_ERROR';

export default SET_CONSUMABLES;
