export const SET_CONSUMABLES = 'SET_CONSUMABLES';
export const RESET_UPDATE_CONSUMABLE_BULK = 'RESET_UPDATE_CONSUMABLE_BULK';
export const POST_UPDATE_CONSUMABLE_START_BULK = 'POST_UPDATE_CONSUMABLE_START_BULK';
export const POST_UPDATE_CONSUMABLE_END_BULK = 'POST_UPDATE_CONSUMABLE_END_BULK';
export const POST_UPDATE_CONSUMABLE_ERROR_BULK = 'POST_UPDATE_CONSUMABLE_ERROR_BULK';
export default SET_CONSUMABLES;
