export const FETCH_COST_BREAKDOWN_START = 'FETCH_COST_BREAKDOWN_START';
export const FETCH_COST_BREAKDOWN_SUCCESS = 'FETCH_COST_BREAKDOWN_SUCCESS';
export const FETCH_COST_BREAKDOWN_ERROR = 'FETCH_COST_BREAKDOWN_ERROR';

export const FETCH_COST_DETAIL_START = 'FETCH_COST_DETAIL_START';
export const FETCH_COST_DETAIL_SUCCESS = 'FETCH_COST_DETAIL_SUCCESS';
export const FETCH_COST_DETAIL_ERROR = 'FETCH_COST_DETAIL_ERROR';

export const CLEAR_COST_DETAIL = 'CLEAR_COST_DETAIL';
