export const GET_EQUIPMENT_BY_ID = 'GET_EQUIPMENT_BY_ID';
export const SET_EQUIPMENTS = 'SET_EQUIPMENTS';
export const UPDATE_EQUIPMENT_START = 'UPDATE_EQUIPMENT_START';
export const UPDATE_EQUIPMENT_SUCCESS = 'UPDATE_EQUIPMENT_SUCCESS';
export const UPDATE_EQUIPMENT_ERROR = 'UPDATE_EQUIPMENT_ERROR';

export default GET_EQUIPMENT_BY_ID;
