const GET_MATERIAL_TYPES = 'GET_MATERIAL_TYPES';
export const GET_EQUIPMENT_TYPES = 'GET_EQUIPMENT_TYPES';
export const GET_REUSABLE_TYPES = 'GET_REUSABLE_TYPES';
export const GET_TOOL_TYPES = 'GET_TOOL_TYPES';
export const GET_CONSUMABLE_TYPES = 'GET_CONSUMABLE_TYPES';
export const FETCH_BUILDING_MATERIAL_INVENTORY_TYPES = 'FETCH_BUILDING_MATERIAL_INVENTORY_TYPES';
export const POST_BUILDING_MATERIAL_INVENTORY_TYPE = 'POST_BUILDING_MATERIAL_INVENTORY_TYPE';
export const RESET_POST_BUILDING_MATERIAL_INVENTORY_TYPE =
  'RESET_POST_BUILDING_MATERIAL_INVENTORY_TYPE';
export const FETCH_BUILDING_MATERIAL_INVENTORY_UNITS = 'FETCH_BUILDING_MATERIAL_INVENTORY_UNITS';
export const POST_BUILDING_MATERIAL_INVENTORY_UNIT = 'POST_BUILDING_MATERIAL_INVENTORY_UNIT';
export const RESET_POST_BUILDING_MATERIAL_INVENTORY_UNIT =
  'RESET_POST_BUILDING_MATERIAL_INVENTORY_UNIT';
export const POST_ERROR_BUILDING_MATERIAL_INVENTORY_TYPE =
  'POST_ERROR_BUILDING_MATERIAL_INVENTORY_TYPE';
export const POST_BUILDING_CONSUMABLE_INVENTORY_TYPE = 'POST_BUILDING_CONSUMABLE_INVENTORY_TYPE';
export const POST_ERROR_BUILDING_CONSUMABLE_INVENTORY_TYPE =
  'POST_ERROR_BUILDING_CONSUMABLE_INVENTORY_TYPE';
export const RESET_POST_BUILDING_CONSUMABLE_INVENTORY_TYPE =
  'RESET_POST_BUILDING_CONSUMABLE_INVENTORY_TYPE';
export const POST_BUILDING_TOOL_INVENTORY_TYPE = 'POST_BUILDING_TOOL_INVENTORY_TYPE';
export const POST_ERROR_BUILDING_TOOL_INVENTORY_TYPE = 'POST_ERROR_BUILDING_TOOL_INVENTORY_TYPE';
export const RESET_POST_BUILDING_TOOL_INVENTORY_TYPE = 'RESET_POST_BUILDING_TOOL_INVENTORY_TYPE';
export const GET_INV_BY_TYPE = 'GET_INV_BY_TYPE';

// Update and Delete constants for inventory types
export const UPDATE_INVENTORY_TYPE = 'UPDATE_INVENTORY_TYPE';
export const UPDATE_INVENTORY_TYPE_SUCCESS = 'UPDATE_INVENTORY_TYPE_SUCCESS';
export const UPDATE_INVENTORY_TYPE_ERROR = 'UPDATE_INVENTORY_TYPE_ERROR';
export const DELETE_INVENTORY_TYPE = 'DELETE_INVENTORY_TYPE';
export const DELETE_INVENTORY_TYPE_SUCCESS = 'DELETE_INVENTORY_TYPE_SUCCESS';
export const DELETE_INVENTORY_TYPE_ERROR = 'DELETE_INVENTORY_TYPE_ERROR';

// Update and Delete constants for inventory units
export const UPDATE_INVENTORY_UNIT = 'UPDATE_INVENTORY_UNIT';
export const DELETE_INVENTORY_UNIT = 'DELETE_INVENTORY_UNIT';
export const DELETE_INVENTORY_UNIT_SUCCESS = 'DELETE_INVENTORY_UNIT_SUCCESS';
export const DELETE_INVENTORY_UNIT_ERROR = 'DELETE_INVENTORY_UNIT_ERROR';

// Add inventory type (generic)
export const ADD_INVENTORY_TYPE = 'ADD_INVENTORY_TYPE';
export const ADD_INVENTORY_TYPE_SUCCESS = 'ADD_INVENTORY_TYPE_SUCCESS';
export const ADD_INVENTORY_TYPE_ERROR = 'ADD_INVENTORY_TYPE_ERROR';

export default GET_MATERIAL_TYPES;
