const GET_MATERIAL_TYPES = 'GET_MATERIAL_TYPES';
export const GET_REUSABLE_TYPES = 'GET_REUSABLE_TYPES';
export const GET_TOOL_TYPES = 'GET_TOOL_TYPES';
export const GET_CONSUMABLE_TYPES = 'GET_CONSUMABLE_TYPES';
export const FETCH_BUILDING_MATERIAL_INVENTORY_TYPES = 'FETCH_BUILDING_MATERIAL_INVENTORY_TYPES';
export const POST_BUILDING_MATERIAL_INVENTORY_TYPE = 'POST_BUILDING_MATERIAL_INVENTORY_TYPE';
export const RESET_POST_BUILDING_MATERIAL_INVENTORY_TYPE =
  'RESET_POST_BUILDING_MATERIAL_INVENTORY_TYPE';
export const FETCH_BUILDING_MATERIAL_INVENTORY_UNITS = 'FETCH_BUILDING_MATERIAL_INVENTORY_UNITS';
export const POST_BUILDING_MATERIAL_INVENTORY_UNIT = 'POST_BUILDING_MATERIAL_INVENTORY_UNIT';
export const RESET_POST_BUILDING_MATERIAL_INVENTORY_UNIT =
  'RESET_POST_BUILDING_MATERIAL_INVENTORY_UNIT';
export const POST_ERROR_BUILDING_MATERIAL_INVENTORY_TYPE =
  'POST_ERROR_BUILDING_MATERIAL_INVENTORY_TYPE';
export const POST_BUILDING_CONSUMABLE_INVENTORY_TYPE = 'POST_BUILDING_CONSUMABLE_INVENTORY_TYPE';
export const POST_ERROR_BUILDING_CONSUMABLE_INVENTORY_TYPE =
  'POST_ERROR_BUILDING_CONSUMABLE_INVENTORY_TYPE';
export const RESET_POST_BUILDING_CONSUMABLE_INVENTORY_TYPE =
  'RESET_POST_BUILDING_CONSUMABLE_INVENTORY_TYPE';
export const GET_INV_BY_TYPE = 'GET_INV_BY_TYPE';
export default GET_MATERIAL_TYPES;
