export const FETCH_ISSUES_SUMMARY_REQUEST = 'FETCH_ISSUES_SUMMARY_REQUEST';
export const FETCH_ISSUES_SUMMARY_SUCCESS = 'FETCH_ISSUES_SUMMARY_SUCCESS';
export const FETCH_ISSUES_SUMMARY_FAILURE = 'FETCH_ISSUES_SUMMARY_FAILURE';

export const FETCH_ISSUES_TREND_REQUEST = 'FETCH_ISSUES_TREND_REQUEST';
export const FETCH_ISSUES_TREND_SUCCESS = 'FETCH_ISSUES_TREND_SUCCESS';
export const FETCH_ISSUES_TREND_FAILURE = 'FETCH_ISSUES_TREND_FAILURE';
