// issueConstants.js
export const FETCH_ISSUES_BARCHART_REQUEST = 'FETCH_ISSUES_BARCHART_REQUEST';
export const FETCH_ISSUES_BARCHART_SUCCESS = 'FETCH_ISSUES_BARCHART_SUCCESS';
export const FETCH_ISSUES_BARCHART_FAILURE = 'FETCH_ISSUES_BARCHART_FAILURE';

export const FETCH_ISSUE_TYPES_YEARS_REQUEST = 'FETCH_ISSUE_TYPES_YEARS_REQUEST';
export const FETCH_ISSUE_TYPES_YEARS_SUCCESS = 'FETCH_ISSUE_TYPES_YEARS_SUCCESS';
export const FETCH_ISSUE_TYPES_YEARS_FAILURE = 'FETCH_ISSUE_TYPES_YEARS_FAILURE';
