// issueConstants.js
export const FETCH_ISSUES_BARCHART_REQUEST = 'FETCH_ISSUES_BARCHART_REQUEST';
export const FETCH_ISSUES_BARCHART_SUCCESS = 'FETCH_ISSUES_BARCHART_SUCCESS';
export const FETCH_ISSUES_BARCHART_FAILURE = 'FETCH_ISSUES_BARCHART_FAILURE';

export const FETCH_ISSUE_TYPES_YEARS_REQUEST = 'FETCH_ISSUE_TYPES_YEARS_REQUEST';
export const FETCH_ISSUE_TYPES_YEARS_SUCCESS = 'FETCH_ISSUE_TYPES_YEARS_SUCCESS';
export const FETCH_ISSUE_TYPES_YEARS_FAILURE = 'FETCH_ISSUE_TYPES_YEARS_FAILURE';

export const FETCH_LONGEST_OPEN_ISSUES_REQUEST = 'FETCH_LONGEST_OPEN_ISSUES_REQUEST';
export const FETCH_LONGEST_OPEN_ISSUES_SUCCESS = 'FETCH_LONGEST_OPEN_ISSUES_SUCCESS';
export const FETCH_LONGEST_OPEN_ISSUES_FAILURE = 'FETCH_LONGEST_OPEN_ISSUES_FAILURE';

export const FETCH_MOST_EXPENSIVE_ISSUES_REQUEST = 'FETCH_MOST_EXPENSIVE_ISSUES_REQUEST';
export const FETCH_MOST_EXPENSIVE_ISSUES_SUCCESS = 'FETCH_MOST_EXPENSIVE_ISSUES_SUCCESS';
export const FETCH_MOST_EXPENSIVE_ISSUES_FAILURE = 'FETCH_MOST_EXPENSIVE_ISSUES_FAILURE';
