// issueConstants.js
export const FETCH_ISSUES_BARCHART_REQUEST = 'FETCH_ISSUES_BARCHART_REQUEST';
export const FETCH_ISSUES_BARCHART_SUCCESS = 'FETCH_ISSUES_BARCHART_SUCCESS';
export const FETCH_ISSUES_BARCHART_FAILURE = 'FETCH_ISSUES_BARCHART_FAILURE';
export const FETCH_LONGEST_OPEN_ISSUES_REQUEST = 'FETCH_LONGEST_OPEN_ISSUES_REQUEST';
export const FETCH_LONGEST_OPEN_ISSUES_SUCCESS = 'FETCH_LONGEST_OPEN_ISSUES_SUCCESS';
export const FETCH_LONGEST_OPEN_ISSUES_FAILURE = 'FETCH_LONGEST_OPEN_ISSUES_FAILURE';
export const SET_DATE_FILTER = 'SET_DATE_FILTER';
export const SET_PROJECT_FILTER = 'SET_PROJECT_FILTER';
