export const SUBMIT_NEW_LESSON_PLAN_REQUEST = 'SUBMIT_NEW_LESSON_PLAN_REQUEST';
export const SUBMIT_NEW_LESSON_PLAN_SUCCESS = 'SUBMIT_NEW_LESSON_PLAN_SUCCESS';
export const SUBMIT_NEW_LESSON_PLAN_FAILURE = 'SUBMIT_NEW_LESSON_PLAN_FAILURE';

export const VIEW_LESSON_PLAN_DRAFT_REQUEST = 'VIEW_LESSON_PLAN_DRAFT_REQUEST';
export const VIEW_LESSON_PLAN_DRAFT_SUCCESS = 'VIEW_LESSON_PLAN_DRAFT_SUCCESS';
export const VIEW_LESSON_PLAN_DRAFT_FAILURE = 'VIEW_LESSON_PLAN_DRAFT_FAILURE';

export const UPDATE_LESSON_PLAN_DRAFT_REQUEST = 'UPDATE_LESSON_PLAN_DRAFT_REQUEST';
export const UPDATE_LESSON_PLAN_DRAFT_SUCCESS = 'UPDATE_LESSON_PLAN_DRAFT_SUCCESS';
export const UPDATE_LESSON_PLAN_DRAFT_FAILURE = 'UPDATE_LESSON_PLAN_DRAFT_FAILURE';
