export const FETCH_LESSON_PLAN_TEMPLATES_REQUEST = 'FETCH_LESSON_PLAN_TEMPLATES_REQUEST';
export const FETCH_LESSON_PLAN_TEMPLATES_SUCCESS = 'FETCH_LESSON_PLAN_TEMPLATES_SUCCESS';
export const FETCH_LESSON_PLAN_TEMPLATES_FAIL = 'FETCH_LESSON_PLAN_TEMPLATES_FAIL';

export const SUBMIT_LESSON_PLAN_DRAFT = 'SUBMIT_LESSON_PLAN_DRAFT';
export const VIEW_LESSON_PLAN_DRAFT = 'VIEW_LESSON_PLAN_DRAFT';
