export const FETCH_LESSON_PLAN_TEMPLATES_REQUEST = 'FETCH_LESSON_PLAN_TEMPLATES_REQUEST';
export const FETCH_LESSON_PLAN_TEMPLATES_SUCCESS = 'FETCH_LESSON_PLAN_TEMPLATES_SUCCESS';
export const FETCH_LESSON_PLAN_TEMPLATES_FAIL = 'FETCH_LESSON_PLAN_TEMPLATES_FAIL';

export const SAVE_LESSON_PLAN_DRAFT_REQUEST = 'SAVE_LESSON_PLAN_DRAFT_REQUEST';
export const SAVE_LESSON_PLAN_DRAFT_SUCCESS = 'SAVE_LESSON_PLAN_DRAFT_SUCCESS';
export const SAVE_LESSON_PLAN_DRAFT_FAIL = 'SAVE_LESSON_PLAN_DRAFT_FAIL';

export const SUBMIT_LESSON_PLAN_DRAFT = 'SUBMIT_LESSON_PLAN_DRAFT';
export const VIEW_LESSON_PLAN_DRAFT = 'VIEW_LESSON_PLAN_DRAFT';
