export const SET_MATERIALS = 'SET_MATERIALS';
export const SET_USER_PROJECTS = 'SET_USER_PROJECTS';
export const RESET_UPDATE_MATERIAL = 'RESET_UPDATE_MATERIAL';
export const POST_UPDATE_MATERIAL_START = 'POST_UPDATE_MATERIAL_START';
export const POST_UPDATE_MATERIAL_END = 'POST_UPDATE_MATERIAL_END';
export default SET_MATERIALS;
