export const SET_REUSABLES = 'SET_REUSABLES';

export const RESET_UPDATE_REUSABLE = 'RESET_UPDATE_REUSABLE';
export const POST_UPDATE_REUSABLE_START = 'POST_UPDATE_REUSABLE_START';
export const POST_UPDATE_REUSABLE_END = 'POST_UPDATE_REUSABLE_END';
export const POST_UPDATE_REUSABLE_ERROR = 'POST_UPDATE_REUSABLE_ERROR';

export const RESET_UPDATE_REUSABLE_BULK = 'RESET_UPDATE_REUSABLE_BULK';
export const POST_UPDATE_REUSABLE_START_BULK = 'POST_UPDATE_REUSABLE_START_BULK';
export const POST_UPDATE_REUSABLE_END_BULK = 'POST_UPDATE_REUSABLE_END_BULK';
export const POST_UPDATE_REUSABLE_ERROR_BULK = 'POST_UPDATE_REUSABLE_ERROR_BULK';

export default SET_REUSABLES;
