export const SET_TOOLS = 'SET_TOOLS';

export const RESET_UPDATE_TOOL = 'RESET_UPDATE_TOOL';
export const POST_UPDATE_TOOL_START = 'POST_UPDATE_TOOL_START';
export const POST_UPDATE_TOOL_END = 'POST_UPDATE_TOOL_END';
export const POST_UPDATE_TOOL_ERROR = 'POST_UPDATE_TOOL_ERROR';

export const RESET_UPDATE_TOOL_BULK = 'RESET_UPDATE_TOOL_BULK';
export const POST_UPDATE_TOOL_START_BULK = 'POST_UPDATE_TOOL_START_BULK';
export const POST_UPDATE_TOOL_END_BULK = 'POST_UPDATE_TOOL_END_BULK';
export const POST_UPDATE_TOOL_ERROR_BULK = 'POST_UPDATE_TOOL_ERROR_BULK';

export default SET_TOOLS;
