export const SET_PROJECT_FILTER = 'SET_PROJECT_FILTER';
export const SET_DATE_RANGE_FILTER = 'SET_DATE_RANGE_FILTER';
export const SET_COMPARISON_PERIOD_FILTER = 'SET_COMPARISON_PERIOD_FILTER';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_COST_BREAKDOWN = 'GET_COST_BREAKDOWN';
