export const FETCH_REVIEWS_INSIGHTS_REQUEST = 'FETCH_REVIEWS_INSIGHTS_REQUEST';
export const FETCH_REVIEWS_INSIGHTS_SUCCESS = 'FETCH_REVIEWS_INSIGHTS_SUCCESS';
export const FETCH_REVIEWS_INSIGHTS_FAILURE = 'FETCH_REVIEWS_INSIGHTS_FAILURE';
