// TODO: Replace mock data with real API call from the backend
const PRData = [
  { prNumber: 'PR 101', reviewCount: 17, title: 'Fix login bug' },
  { prNumber: 'PR 102', reviewCount: 8, title: 'Add dashboard' },
  { prNumber: 'PR 103', reviewCount: 23, title: 'Refactor API' },
  { prNumber: 'PR 104', reviewCount: 35, title: 'Improve error handling' },
  { prNumber: 'PR 105', reviewCount: 12, title: 'Add new feature' },
  { prNumber: 'PR 106', reviewCount: 29, title: 'Fix styling issue' },
  { prNumber: 'PR 107', reviewCount: 3, title: 'Update documentation' },
  { prNumber: 'PR 108', reviewCount: 40, title: 'Optimize performance' },
  { prNumber: 'PR 109', reviewCount: 14, title: 'Refactor code' },
  { prNumber: 'PR 110', reviewCount: 27, title: 'Add new component' },
  { prNumber: 'PR 111', reviewCount: 6, title: 'Add new feature' },
  { prNumber: 'PR 112', reviewCount: 19, title: 'Fix styling issue' },
  { prNumber: 'PR 113', reviewCount: 32, title: 'Update documentation' },
  { prNumber: 'PR 114', reviewCount: 11, title: 'Optimize performance' },
  { prNumber: 'PR 115', reviewCount: 25, title: 'Refactor code' },
  { prNumber: 'PR 116', reviewCount: 7, title: 'Add new component' },
  { prNumber: 'PR 117', reviewCount: 38, title: 'Add new feature' },
  { prNumber: 'PR 118', reviewCount: 21, title: 'Fix styling issue' },
  { prNumber: 'PR 119', reviewCount: 2, title: 'Update documentation' },
  { prNumber: 'PR 120', reviewCount: 36, title: 'Optimize performance' },
  { prNumber: 'PR 121', reviewCount: 10, title: 'Refactor code' },
  { prNumber: 'PR 122', reviewCount: 31, title: 'Add new component' },
  { prNumber: 'PR 123', reviewCount: 15, title: 'Add new feature' },
  { prNumber: 'PR 124', reviewCount: 24, title: 'Fix styling issue' },
  { prNumber: 'PR 125', reviewCount: 9, title: 'Update documentation' },
  { prNumber: 'PR 126', reviewCount: 39, title: 'Optimize performance' },
  { prNumber: 'PR 127', reviewCount: 5, title: 'Refactor code' },
  { prNumber: 'PR 128', reviewCount: 28, title: 'Add new component' },
  { prNumber: 'PR 129', reviewCount: 13, title: 'Add new feature' },
  { prNumber: 'PR 130', reviewCount: 22, title: 'Fix styling issue' },
  { prNumber: 'PR 131', reviewCount: 34, title: 'Update documentation' },
  { prNumber: 'PR 132', reviewCount: 16, title: 'Optimize performance' },
  { prNumber: 'PR 133', reviewCount: 1, title: 'Refactor code' },
  { prNumber: 'PR 134', reviewCount: 30, title: 'Add new component' },
  { prNumber: 'PR 135', reviewCount: 18, title: 'Add new feature' },
  { prNumber: 'PR 136', reviewCount: 26, title: 'Fix styling issue' },
  { prNumber: 'PR 137', reviewCount: 4, title: 'Update documentation' },
  { prNumber: 'PR 138', reviewCount: 33, title: 'Optimize performance' },
  { prNumber: 'PR 139', reviewCount: 20, title: 'Refactor code' },
  { prNumber: 'PR 140', reviewCount: 37, title: 'Add new component' },
  { prNumber: 'PR 141', reviewCount: 12, title: 'Add new feature' },
  { prNumber: 'PR 142', reviewCount: 8, title: 'Fix styling issue' },
  { prNumber: 'PR 143', reviewCount: 19, title: 'Update documentation' },
  { prNumber: 'PR 144', reviewCount: 23, title: 'Optimize performance' },
  { prNumber: 'PR 145', reviewCount: 6, title: 'Refactor code' },
  { prNumber: 'PR 146', reviewCount: 29, title: 'Add new component' },
  { prNumber: 'PR 147', reviewCount: 40, title: 'Add new feature' },
  { prNumber: 'PR 148', reviewCount: 17, title: 'Fix styling issue' },
  { prNumber: 'PR 149', reviewCount: 27, title: 'Update documentation' },
  { prNumber: 'PR 150', reviewCount: 14, title: 'Optimize performance' },
];

export default PRData;
