import configureStore from 'redux-mock-store';
import thunk from 'redux-thunk';
import { Provider } from 'react-redux';
import { render, screen } from '@testing-library/react';
import BadgeManagement from './BadgeManagement';

const mockStore = configureStore([thunk]);

const mockData = {
  alertVisible: false,
  allBadgeData: [
    {
      _id: 'abc1',
      badgeName: '30 HOURS 3-WEEK STREAK',
      category: 'Stewardship',
      imageUrl: 'https://www.test.com/30-HOURS-STREAK-3-WEEKS-200-PX.png',
      ranking: 118,
      description:
        'Contributing 30 hours for one week is impressive. Doing it for 3 weeks in a row is absolutely amazing! Well done!',
      months: null,
      multiple: null,
      people: null,
      totalHrs: 30,
      type: 'X Hours for X Week Streak',
      weeks: 3,
      showReport: true,
    },
    {
      _id: 'abc2',
      badgeName: 'LEAD A TEAM OF 40+ (Trailblazer)',
      category: 'Stewardship',
      imageUrl: 'https://www.test.com/LEADER-OF-40-PLUS-TEAM-TRAILBLAZER-200-PX.png',
      ranking: 53,
      description:
        'You are a leader! More specifically, you’ve led a team of 40 people or more as a member of One Community. Fantastic work!',
      months: null,
      multiple: null,
      people: 40,
      totalHrs: null,
      type: 'Lead a team of X+',
      weeks: null,
    },
  ],
  color: null,
  message: '',
  role: 'Owner',
};

const renderComponent = mockProps => {
  const store = mockStore({
    badge: {
      alertVisible: mockProps.alertVisible,
      allBadgeData: mockProps.allBadgeData,
      color: mockProps.color,
      message: mockProps.message,
    },
    allProjects: {
      projects: [],
    },
    userProfile: {
      role: mockProps.role,
    },
    allUserProfiles: {
      fetching: false,
      fetched: true,
      userProfiles: [
        {
          isActive: true,
          weeklycommittedHours: 0,
          _id: '5c4cc2109487b0003924f1e3',
          role: 'Administrator',
          firstName: 'Test',
          lastName: 'Admin',
          email: 'onecommunityglobal@gmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 20,
          _id: '5e2cc6df7a91aaf820510a55',
          role: 'Volunteer',
          firstName: 'Sidd',
          lastName: 'Admin',
          email: 'devadmin@live.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5ede6be453a0480017164a5b',
          role: 'Administrator',
          firstName: 'Nithesh',
          lastName: 'Admin',
          email: 'nithuan141@gmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5edf141c78f1380017b829a6',
          role: 'Administrator',
          firstName: 'Dev',
          lastName: 'Admin',
          email: 'devadmin@hgn.net',
        },
        {
          isActive: true,
          weeklycommittedHours: 15,
          _id: '5f20d19160bd1734f069dadb',
          role: 'Administrator',
          firstName: 'Jerry',
          lastName: 'Administrator',
          email: 'jerryadmin@example.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5be0952c633dae0016081b4b',
          role: 'Administrator',
          firstName: 'Tyler',
          lastName: 'Calvert',
          email: 'tyjcalvert@gmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 0,
          _id: '5bef421d908c1b0038d06dbd',
          role: 'Administrator',
          firstName: 'Adam',
          lastName: 'Capdeville',
          email: 'agcapdeville@gmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 2,
          _id: '5e2a76cb0441c30039a6909a',
          role: 'Volunteer',
          firstName: 'Test',
          lastName: 'Cat',
          email: 'testcat@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 10,
          _id: '5ef771cf612d522c54f9b637',
          role: 'Volunteer',
          firstName: 'Testing',
          lastName: 'Delete',
          email: 'testing.delete@example.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 3,
          _id: '5eff58c34c9f52001786f031',
          role: 'Volunteer',
          firstName: 'Test',
          lastName: 'Delete',
          email: 'td@td.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5b3013287275b6002e3b2de4',
          role: 'Volunteer',
          firstName: 'Dipti',
          lastName: 'Dhondarkar',
          email: 'DiptiDhondarkar@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5b3013087275b6002e3b2de3',
          role: 'Volunteer',
          firstName: 'Dehua',
          lastName: 'Feng',
          email: 'dehuafeng@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5b3013847275b6002e3b2de7',
          role: 'Volunteer',
          firstName: 'Michael',
          lastName: 'Hagler',
          email: 'MichaelHagler@yopmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5e9fa3d9b5dc3c2e48c10989',
          role: 'Manager',
          firstName: 'Alvaro',
          lastName: 'Hernández',
          email: 'alaherma@mail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5b3013f57275b6002e3b2dea',
          role: 'Volunteer',
          firstName: 'Mike',
          lastName: 'Hogan',
          email: 'MikeHogan@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5ae0badeb3f1241c28c9b4e3',
          role: 'Volunteer',
          firstName: 'Swathy',
          lastName: 'Jayaseelan',
          email: 'SwathyJayaseelan@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5b30136d7275b6002e3b2de6',
          role: 'Volunteer',
          firstName: 'Michael',
          lastName: 'Kowalski',
          email: 'MichaelKowalski@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5b3013c47275b6002e3b2de9',
          role: 'Volunteer',
          firstName: 'Yun',
          lastName: 'Lin',
          email: 'YunLin@yopmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5ea5ba581446e1164098fa7b',
          role: 'Manager',
          firstName: 'New',
          lastName: 'Manager',
          email: 'new.manager@example.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 15,
          _id: '5f20d18660bd1734f069dada',
          role: 'Manager',
          firstName: 'Jerry',
          lastName: 'Manager',
          email: 'jerrymanager@example.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5b0585ffd68f7f002dbcf4de',
          role: 'Administrator',
          firstName: 'Sowmya',
          lastName: 'Manohar',
          email: 'sowmisarojini@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5be0964d633dae0016081b4c',
          role: 'Administrator',
          firstName: 'Jordan',
          lastName: 'Miller',
          email: 'jordan@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 20,
          _id: '5ae0afcab3f1241c28c9b4e2',
          role: 'Administrator',
          firstName: 'Shubhra',
          lastName: 'Mittal2',
          email: 'shubhra.goel@gmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5eddbcd353a0480017164a57',
          role: 'Administrator',
          firstName: 'Admin',
          lastName: 'New',
          email: 'ss@ram.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 10,
          _id: '5eddc35953a0480017164a58',
          role: 'Administrator',
          firstName: 'AdminTest',
          lastName: 'New',
          email: 'ss@admin.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 16,
          _id: '5e1a685add8cea0ea3420141',
          role: 'Administrator',
          firstName: 'Henry',
          lastName: 'Nguyen',
          email: 'thankyouforyouremail3000@gmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5bad2979e168140090176793',
          role: 'Volunteer',
          firstName: 'Emilio',
          lastName: 'Nájera',
          email: 'emilionájera@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5bec67ee0df8050016d2e21c',
          role: 'Volunteer',
          firstName: 'Ram',
          lastName: 'Ram',
          email: 'ram@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5bc4f3d1476a8e009034264c',
          role: 'Core Team',
          firstName: 'Sara',
          lastName: 'Sabol',
          email: 'sarasabol@yopmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 30,
          _id: '5ab1713bba0e82002b182206',
          role: 'Administrator',
          firstName: 'Jae',
          lastName: 'Sabol',
          email: 'jae@onecommunityglobal.org',
        },
        {
          isActive: true,
          weeklycommittedHours: 20,
          _id: '5e28bdaab9ec7807f278aea3',
          role: 'Manager',
          firstName: 'Rafel',
          lastName: 'Sabol',
          email: 'jae123s33@mail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5bad3c06e168140090176794',
          role: 'Administrator',
          firstName: 'Aishwaryasads',
          lastName: 'Singh',
          email: 'aishwarya.singh1202@gmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5bc4f438476a8e009034264d',
          role: 'Core Team',
          firstName: 'Bear',
          lastName: 'Stauss',
          email: 'BearStauss@YOPMAIL.COM',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5edda90b53a0480017164a4e',
          role: 'Administrator',
          firstName: 'Nithesh',
          lastName: 'TEK',
          email: 'getnithesh@gmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5baac381e16814009017678c',
          role: 'Volunteer',
          firstName: 'Jae',
          lastName: 'Test',
          email: 'one.community@me.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5ef2bf59b4c1a9648d685b0d',
          role: 'Core Team',
          firstName: 'Ada',
          lastName: 'Test',
          email: 'ada.test@gmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5ec95665c77af83f146f339b',
          role: 'Administrator',
          firstName: 'Andon',
          lastName: 'Testing',
          email: 'andon.testing@example.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5bd77898a41ad772b60d2d3a',
          firstName: 'TimeArchiveAccount',
          lastName: 'TimeArchiveAccount',
          email: 'timearchiveaccount@yopmail.com',
          role: 'Volunteer',
        },
        {
          isActive: true,
          weeklycommittedHours: 5,
          _id: '5f150b7599b77700174e69fb',
          role: 'Volunteer',
          firstName: 'Nithesh',
          lastName: 'Train',
          email: 'ntr@example.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5b3013a57275b6002e3b2de8',
          role: 'Volunteer',
          firstName: 'Lucas',
          lastName: 'Tsutsui da Silva',
          email: 'LucasTsutsui da Silva@yopmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 0,
          _id: '5c63038e2b88c00039ed79e6',
          role: 'Volunteer',
          firstName: 'Test',
          lastName: 'User',
          email: 'testuser@test.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5eb2c7e9f0eb3233382d232e',
          role: 'Administrator',
          firstName: 'NewAdmin',
          lastName: 'User',
          email: 'new.admin@example.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 10,
          _id: '5ea5ed991446e1164098fa7c',
          role: 'Administrator',
          firstName: 'New',
          lastName: 'User100',
          email: 'newuser100@example.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5ea5b0d81446e1164098fa7a',
          role: 'Manager',
          firstName: 'Test',
          lastName: 'User99',
          email: 'test.user99@example.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 5,
          _id: '5ee257d03f0d66001704f8aa',
          role: 'Volunteer',
          firstName: 'Dev',
          lastName: 'Volunteer',
          email: 'devvolunteer@hgn.net',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5eecff1e80d46831c828ed86',
          role: 'Volunteer',
          firstName: 'Adam',
          lastName: 'Volunteer',
          email: 'adamc.testing@example.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 15,
          _id: '5f20d17260bd1734f069dad9',
          role: 'Volunteer',
          firstName: 'Jerry',
          lastName: 'Volunteer',
          email: 'jerryvolunteer@example.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 10,
          _id: '5e115150c472127fee9ed87d',
          role: 'Administrator',
          firstName: 'Tengxiao',
          lastName: 'Wang',
          email: 'tengxiaowang@yopmail.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 20,
          _id: '5e16ba934ef6251c89149096',
          role: 'Manager',
          firstName: 'Ron',
          lastName: 'Weasely',
          email: 'siddharth.gore@live.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 20,
          _id: '5e2e3d3d51ddad1693d79279',
          role: 'Volunteer',
          firstName: 'Simon',
          lastName: 'Xiong',
          email: 'simonxiong11@gmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 20,
          _id: '5e66cdf5336b3af7f2466d2b',
          role: 'Administrator',
          firstName: 'Wen',
          lastName: 'Zhang',
          email: 'wenzhang@yopmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 15,
          _id: '5f1fb5d9974f146edcfa741b',
          role: 'Manager',
          firstName: 'Jerry',
          lastName: 'Zhang',
          email: 'jerryzhang.dev@gmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 0,
          _id: '5bde804fb2d9e00016c47fd1',
          role: 'Volunteer',
          firstName: 'sddf',
          lastName: 'fsdfsdf',
          email: 'dsd@tyy.com',
        },
        {
          isActive: false,
          weeklycommittedHours: 0,
          _id: '5beca51d3d07ed00166deaa1',
          role: 'Volunteer',
          firstName: 'ram2',
          lastName: 'ram',
          email: 'ram.k@yopmail.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 20,
          _id: '5e2cc7087a91aaf820510a56',
          role: 'Volunteer',
          firstName: 'Dev',
          lastName: 'user1',
          email: 'devUser1@live.com',
        },
        {
          isActive: true,
          weeklycommittedHours: 20,
          _id: '5e9fa2fbb3acfb7f9a4d1d8c',
          role: 'Volunteer',
          firstName: 'Alvaro',
          lastName: 'user1',
          email: 'alvaro@gmail.com',
        },
      ],
      status: '200',
    },
  });

  render(
    <Provider store={store}>
      <BadgeManagement />
    </Provider>
  );
};

describe('Badge Management Tests', () => {
  it('should toggle active class based on state', () => {
    renderComponent(mockData);
    // Check if the NavLink for 'Badge Assignment' has the active class initially
    expect(screen.getByText('Badge Assignment').closest('a')).toHaveClass('active');
  });
});