export const FETCH_PROPERTY_DETAILS_BEGIN = 'FETCH_PROPERTY_DETAILS_BEGIN';
export const FETCH_PROPERTY_DETAILS_SUCCESS = 'FETCH_PROPERTY_DETAILS_SUCCESS';
export const FETCH_PROPERTY_DETAILS_ERROR = 'FETCH_PROPERTY_DETAILS_ERROR';

export const PLACE_BID_BEGIN = 'PLACE_BID_BEGIN';
export const PLACE_BID_SUCCESS = 'PLACE_BID_SUCCESS';
export const PLACE_BID_ERROR = 'PLACE_BID_ERROR';

export const FETCH_NOTIFICATIONS_BEGIN = 'FETCH_NOTIFICATIONS_BEGIN';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR';
