export const FETCH_UNIT_DETAILS_REQUEST = 'FETCH_UNIT_DETAILS_REQUEST';
export const FETCH_UNIT_DETAILS_SUCCESS = 'FETCH_UNIT_DETAILS_SUCCESS';
export const FETCH_UNIT_DETAILS_FAILURE = 'FETCH_UNIT_DETAILS_FAILURE';

export const SUBMIT_BID_REQUEST = 'SUBMIT_BID_REQUEST';
export const SUBMIT_BID_SUCCESS = 'SUBMIT_BID_SUCCESS';
export const SUBMIT_BID_FAILURE = 'SUBMIT_BID_FAILURE';

export const GENRATE_NOTIFICATION_REQUEST = 'GENRATE_NOTIFICATION_REQUEST';
export const GENRATE_NOTIFICATION_SUCCESS = 'GENRATE_NOTIFICATION_SUCCESS';
export const GENRATE_NOTIFICATION_FAILURE = 'GENRATE_NOTIFICATION_FAILURE';
