export const FETCH_UNIT_DETAILS_REQUEST = 'FETCH_UNIT_DETAILS_REQUEST';
export const FETCH_UNIT_DETAILS_SUCCESS = 'FETCH_UNIT_DETAILS_SUCCESS';
export const FETCH_UNIT_DETAILS_FAILURE = 'FETCH_UNIT_DETAILS_FAILURE';

export const SUBMIT_BID_REQUEST = 'SUBMIT_BID_REQUEST';
export const SUBMIT_BID_SUCCESS = 'SUBMIT_BID_SUCCESS';
export const SUBMIT_BID_FAILURE = 'SUBMIT_BID_FAILURE';

export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';
