export const LISTING_FETCH_REQUEST = 'LISTING_FETCH_REQUEST';
export const LISTING_FETCH_SUCCESS = 'LISTING_FETCH_SUCCESS';
export const LISTING_FETCH_FAIL = 'LISTING_FETCH_FAIL';

export const LISTING_AVAILABILITY_REQUEST = 'LISTING_AVAILABILITY_REQUEST';
export const LISTING_AVAILABILITY_SUCCESS = 'LISTING_AVAILABILITY_SUCCESS';
export const LISTING_AVAILABILITY_FAIL = 'LISTING_AVAILABILITY_FAIL';

export const LISTING_BOOK_REQUEST = 'LISTING_BOOK_REQUEST';
export const LISTING_BOOK_SUCCESS = 'LISTING_BOOK_SUCCESS';
export const LISTING_BOOK_FAIL = 'LISTING_BOOK_FAIL';
export const LISTING_BOOK_RESET = 'LISTING_BOOK_RESET';
