export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_END = 'FETCH_MESSAGES_END';
export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_END = 'SEND_MESSAGE_END';

export const UPDATE_MESSAGES_READ_STATUS = 'UPDATE_MESSAGES_READ_STATUS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS';
export const SEND_MESSAGE_PENDING = 'SEND_MESSAGE_PENDING';