export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const UPDATE_MESSAGE_STATUS_REQUEST = "UPDATE_MESSAGE_STATUS_REQUEST";
export const UPDATE_MESSAGE_STATUS_SUCCESS = "UPDATE_MESSAGE_STATUS_SUCCESS";
export const UPDATE_MESSAGE_STATUS_FAILURE = "UPDATE_MESSAGE_STATUS_FAILURE";

export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED"; // For real-time message reception
export const MESSAGE_STATUS_UPDATED = "MESSAGE_STATUS_UPDATED"; // For real-time status updates