export const FETCH_USER_PREFERENCE_START = 'FETCH_USER_PREFERENCE_START';
export const FETCH_USER_PREFERENCE_END = 'FETCH_USER_PREFERENCE_END';
export const UPDATE_USER_PREFERENCE_START = 'UPDATE_USER_PREFERENCE_START';
export const UPDATE_USER_PREFERENCE_END = 'UPDATE_USER_PREFERENCE_END';
export const FETCH_USER_PREFERENCE_ERROR = 'FETCH_USER_PREFERENCE_ERROR';
export const UPDATE_USER_PREFERENCE_ERROR = 'UPDATE_USER_PREFERENCE_ERROR';
