export const FETCH_ALL_VILLAGES_REQUEST = 'FETCH_ALL_VILLAGES_REQUEST';
export const FETCH_ALL_VILLAGES_SUCCESS = 'FETCH_ALL_VILLAGES_SUCCESS';
export const FETCH_ALL_VILLAGES_FAILURE = 'FETCH_ALL_VILLAGES_FAILURE';
export const FETCH_VILLAGE_DETAILS_REQUEST = 'FETCH_VILLAGE_DETAILS_REQUEST';
export const FETCH_VILLAGE_DETAILS_SUCCESS = 'FETCH_VILLAGE_DETAILS_SUCCESS';
export const FETCH_VILLAGE_DETAILS_FAILURE = 'FETCH_VILLAGE_DETAILS_FAILURE';
