export const FETCH_USER_WISHLIST_REQUEST = 'FETCH_USER_WISHLIST_REQUEST';
export const FETCH_USER_WISHLIST_SUCCESS = 'FETCH_USER_WISHLIST_SUCCESS';
export const FETCH_USER_WISHLIST_FAILURE = 'FETCH_USER_WISHLIST_FAILURE';

export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_FAILURE = 'ADD_TO_WISHLIST_FAILURE';

export const REMOVE_FROM_WISHLIST_REQUEST = 'REMOVE_FROM_WISHLIST_REQUEST';
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';
export const REMOVE_FROM_WISHLIST_FAILURE = 'REMOVE_FROM_WISHLIST_FAILURE';
