export const FETCH_INJURIES_REQUEST = 'FETCH_INJURIES_REQUEST';
export const FETCH_INJURIES_SUCCESS = 'FETCH_INJURIES_SUCCESS';
export const FETCH_INJURIES_FAILURE = 'FETCH_INJURIES_FAILURE';

// Project action types
export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';