export const PermissionPresets = [
    {
        name: 'Owner',
        permissions: [
            'seeUsersInDashboard', 
            'editHeaderMessage',
            'getReports', 
            'getWeeklySummaries', 
            'totalValidWeeklySummaries', 
            'highlightEligibleBios',
            'getVolunteerWeeklySummary',
            'editTeamCode', 
            'getUserProfiles', 
            'postUserProfile', 
            'putUserProfile', 
            'changeUserStatus', 
            'addInfringements', 
            'editInfringements', 
            'deleteInfringements', 
            'putUserProfileImportantInfo', 
            'updateSummaryRequirements', 
            'manageTimeOffRequests', 
            'changeUserRehireableStatus', 
            'seeBadges', 
            'createBadges', 
            'updateBadges', 
            'deleteBadges', 
            'assignBadges', 
            'postProject', 
            'deleteProject', 
            'putProject', 
            'getProjectMembers', 
            'assignProjectToUsers', 
            'postWbs', 
            'deleteWbs', 
            'postTask', 
            'updateTask', 
            'deleteTask', 
            'resolveTask',
            'suggestTask',
            'putReviewStatus',
            'putTeam', 
            'deleteTeam', 
            'postTeam', 
            'assignTeamToUsers', 
            'toggleTangibleTime',
            'postTimeEntry', 
            'deleteTimeEntry', 
            'editTimeEntryTime', 
            'editTimeEntryDescription', 
            'editTimeEntryToggleTangible', 
            'editTimeEntryDate', 
            'sendEmails',
            'postRole',
            'deleteRole',
            'putRole', 
            'putUserProfilePermissions', 
            'updatePopup', 
            'addNewTitle', 
            'assignTitle', 
            'editTitle'
        ],
    },
    {
        name: 'Administrator',
        permissions: [
            'seeUsersInDashboard', 
            'getReports', 
            'getWeeklySummaries', 
            'totalValidWeeklySummaries', 
            'editTeamCode', 
            'getUserProfiles', 
            'postUserProfile', 
            'putUserProfile', 
            'changeUserStatus', 
            'addInfringements', 
            'editInfringements', 
            'deleteInfringements', 
            'putUserProfileImportantInfo', 
            'updateSummaryRequirements', 
            'manageTimeOffRequests', 
            'changeUserRehireableStatus', 
            'seeBadges', 
            'createBadges', 
            'updateBadges', 
            'deleteBadges', 
            'assignBadges', 
            'postProject', 
            'deleteProject', 
            'putProject', 
            'getProjectMembers', 
            'assignProjectToUsers', 
            'postWbs', 
            'deleteWbs', 
            'postTask', 
            'updateTask', 
            'deleteTask', 
            'putTeam', 
            'deleteTeam', 
            'postTeam', 
            'assignTeamToUsers', 
            'postTimeEntry', 
            'deleteTimeEntry', 
            'editTimeEntryTime', 
            'editTimeEntryDescription', 
            'editTimeEntryToggleTangible', 
            'editTimeEntryDate', 
            'putRole', 
            'putUserProfilePermissions', 
            'updatePopup', 
            'addNewTitle', 
            'assignTitle'
        ],
    },
    {
        name: 'Manager',
        permissions: [
            'getUserProfiles', 
            'putUserProfile', 
            'addInfringements', 
            'editInfringements', 
            'deleteInfringements', 
            'getProjectMembers', 
            'postTask', 
            'updateTask', 
            'suggestTask', 
            'putReviewStatus', 
            'putTeam'
        ],
    },
    {
        name: 'Mentor',
        permissions: [
            'getUserProfiles', 
            'putUserProfile', 
            'addInfringements', 
            'editInfringements', 
            'deleteInfringements', 
            'getProjectMembers', 
            'updateTask', 
            'suggestTask', 
            'putReviewStatus'
        ],
    },
    {
        name: 'Core Team',
        permissions: [
            'seeUsersInDashboard', 
            'getReports', 
            'getWeeklySummaries', 
            'getUserProfiles', 
            'getProjectMembers'
        ],
    },
    {
        name: 'SaumitTestTest',
        permissions: [
            'seeUsersInDashboard', 
            'editHeaderMessage', 
            'getReports', 
            'getWeeklySummaries', 
            'totalValidWeeklySummaries', 
            'highlightEligibleBios', 
            'getVolunteerWeeklySummary', 
            'editTeamCode', 
            'getUserProfiles', 
            'postUserProfile', 
            'putUserProfile', 
            'changeUserStatus', 
            'addInfringements', 
            'editInfringements', 
            'deleteInfringements', 
            'putUserProfileImportantInfo', 
            'updateSummaryRequirements', 
            'manageTimeOffRequests', 
            'changeUserRehireableStatus'
        ],
    },
    {
        name: 'TestRole',
        permissions: [
            'getReports', 
            'getWeeklySummaries', 
            'totalValidWeeklySummaries', 
            'highlightEligibleBios', 
            'getVolunteerWeeklySummary', 
            'getUserProfiles', 
            'putUserProfile', 
            'changeUserStatus', 
            'putUserProfilePermissions'
        ],
    },
    {
        name: 'testtst',
        permissions: [
            'seeUsersInDashboard', 
            'editHeaderMessage', 
            'getReports', 
            'getWeeklySummaries', 
            'totalValidWeeklySummaries', 
            'highlightEligibleBios', 
            'getVolunteerWeeklySummary', 
            'editTeamCode'
        ],
    },
    {
        name: 'usethistotest',
        permissions: [
            'totalValidWeeklySummaries', 
            'highlightEligibleBios', 
            'postUserProfile', 
            'putUserProfile', 
            'updateBadges', 
            'deleteBadges'
        ],
    },
    {
        name: 'Creator',
        permissions: ['seeUsersInDashboard', 'getReports'],
    },
    {
        name: 'Test Role 3',
        permissions: [
            'getReports', 
            'getWeeklySummaries', 
            'totalValidWeeklySummaries', 
            'highlightEligibleBios', 
            'getVolunteerWeeklySummary', 
            'editTeamCode'
        ],
    },
    {
        name: 'Assistant Manager',
        permissions: ['suggestTask', 'putReviewStatus'],
    },
    {
        name: 'Volunteer',
        permissions: ['suggestTask'],
    }
]