export const PermissionPresets = [
    {
        name: 'Owner',
        permissions: [

        ],
    },
    {
        name: 'Administrator',
        permissions: [
            'seeUsersInDashboard', 
            'getReports', 
            'getWeeklySummaries', 
            'totalValidWeeklySummaries', 
            'editTeamCode', 
            'getUserProfiles', 
            'postUserProfile', 
            'putUserProfile', 
            'changeUserStatus', 
            'addInfringements', 
            'editInfringements', 
            'deleteInfringements', 
            'putUserProfileImportantInfo', 
            'updateSummaryRequirements', 
            'manageTimeOffRequests', 
            'changeUserRehireableStatus', 
            'seeBadges', 
            'createBadges', 
            'updateBadges', 
            'deleteBadges', 
            'assignBadges', 
            'postProject', 
            'deleteProject', 
            'putProject', 
            'getProjectMembers', 
            'assignProjectToUsers', 
            'postWbs', 
            'deleteWbs', 
            'postTask', 
            'updateTask', 
            'deleteTask', 
            'putTeam', 
            'deleteTeam', 
            'postTeam', 
            'assignTeamToUsers', 
            'postTimeEntry', 
            'deleteTimeEntry', 
            'editTimeEntryTime', 
            'editTimeEntryDescription', 
            'editTimeEntryToggleTangible', 
            'editTimeEntryDate', 
            'putRole', 
            'putUserProfilePermissions', 
            'updatePopup', 
            'addNewTitle', 
            'assignTitle', 
            'editTeamCode', 
            'seeUsersInDashboard'
        ],
    },
    {
        name: 'Manager',
        permissions: [
            'seeUsersInDashboard', 
            'editTeamCode', 
            'getUserProfiles', 
            'putUserProfile', 
            'addInfringements', 
            'editInfringements', 
            'deleteInfringements', 
            'updateSummaryRequirements', 
            'manageTimeOffRequests', 
            'getProjectMembers', 
            'postTask', 
            'updateTask', 
            'suggestTask', 
            'putReviewStatus', 
            'putTeam', 
            'postTimeEntry', 
            'editTimeEntryTime', 
            'editTimeEntryDescription', 
            'editTimeEntryToggleTangible', 
            'editTimeEntryDate', 
            'putUserProfilePermissions', 
            'addNewTitle', 
            'assignTitle', 
            'editTeamCode', 
            'seeUsersInDashboard'
        ],
    },
    {
        name: 'Mentor',
        permissions: [
            'seeUsersInDashboard', 
            'editTeamCode', 
            'getUserProfiles', 
            'putUserProfile', 
            'addInfringements', 
            'editInfringements', 
            'deleteInfringements', 
            'updateSummaryRequirements', 
            'manageTimeOffRequests', 
            'getProjectMembers', 
            'updateTask', 
            'suggestTask', 
            'putReviewStatus', 
            'putTeam', 
            'postTimeEntry', 
            'editTimeEntryTime', 
            'editTimeEntryDescription', 
            'editTimeEntryToggleTangible', 
            'editTimeEntryDate', 
            'putUserProfilePermissions', 
            'addNewTitle', 
            'assignTitle', 
            'editTeamCode', 
            'seeUsersInDashboard'
        ],
    },
    {
        name: 'Core Team',
        permissions: [
            
        ],
    }
]