export const mockRecipes = [
  {
    id: 1,
    name: 'Garden Vegetable Soup',
    type: 'Soup',
    description: 'A hearty soup made with fresh garden vegetables',
    prepTime: 45,
    servings: 6,
    difficulty: 'Easy',
    tags: ['Vegan', 'Gluten-Free', 'Seasonal'],
    hasPriorityIngredients: true,
    onsitePercentage: 85,
    ingredients: [
      { id: 'ing1', name: 'Tomatoes', quantity: '4 cups', isOnsite: true, isAvailable: true },
      { id: 'ing2', name: 'Carrots', quantity: '2 cups', isOnsite: true, isAvailable: true },
      {
        id: 'ing3',
        name: 'Celery',
        quantity: '4 stalks, chopped',
        isOnsite: true,
        isAvailable: true,
      },
      { id: 'ing4', name: 'Onion', quantity: '1 large, diced', isOnsite: true, isAvailable: true },
      {
        id: 'ing5',
        name: 'Garlic',
        quantity: '4 cloves, minced',
        isOnsite: true,
        isAvailable: true,
      },
      {
        id: 'ing6',
        name: 'Zucchini',
        quantity: '2 medium, cubed',
        isOnsite: true,
        isAvailable: true,
      },
      {
        id: 'ing7',
        name: 'Vegetable Broth',
        quantity: '6 cups',
        isOnsite: false,
        isAvailable: true,
      },
      {
        id: 'ing8',
        name: 'Olive Oil',
        quantity: '2 tablespoons',
        isOnsite: false,
        isAvailable: true,
      },
      { id: 'ing9', name: 'Salt', quantity: 'To taste', isOnsite: false, isAvailable: true },
      {
        id: 'ing10',
        name: 'Black Pepper',
        quantity: 'To taste',
        isOnsite: false,
        isAvailable: false,
      },
    ],
    instructions: [
      'Heat olive oil in a large pot over medium heat.',
      'Sauté onion and garlic until softened, about 3-4 minutes.',
      'Add carrots and celery, cook for 5 minutes.',
      'Add zucchini and tomatoes, stir well.',
      'Pour in vegetable broth and bring to a boil.',
      'Reduce heat to low and simmer for 25-30 minutes until all vegetables are tender.',
      'Season with salt and pepper to taste.',
      'Serve hot with crusty bread on the side.',
    ],
  },
  {
    id: 2,
    name: 'Herb Roasted Chicken',
    type: 'Main Course',
    description: 'Chicken seasoned with fresh garden herbs',
    prepTime: 90,
    servings: 4,
    difficulty: 'Medium',
    tags: ['Protein', 'Comfort Food'],
    hasPriorityIngredients: false,
    onsitePercentage: 40,
    ingredients: [
      {
        id: 'ing11',
        name: 'Chicken Breasts',
        quantity: '4 boneless, skinless',
        isOnsite: false,
        isAvailable: true,
      },
      {
        id: 'ing12',
        name: 'Fresh Rosemary',
        quantity: '2 tbsp, chopped',
        isOnsite: true,
        isAvailable: true,
      },
      {
        id: 'ing13',
        name: 'Fresh Thyme',
        quantity: '1 tbsp, chopped',
        isOnsite: true,
        isAvailable: true,
      },
      { id: 'ing14', name: 'Breadcrumbs', quantity: '1 cup', isOnsite: false, isAvailable: false },
      {
        id: 'ing15',
        name: 'Parmesan Cheese',
        quantity: '1/2 cup, grated',
        isOnsite: false,
        isAvailable: false,
      },
      {
        id: 'ing16',
        name: 'Olive Oil',
        quantity: '3 tablespoons',
        isOnsite: false,
        isAvailable: true,
      },
      {
        id: 'ing17',
        name: 'Garlic Powder',
        quantity: '1 teaspoon',
        isOnsite: false,
        isAvailable: true,
      },
      { id: 'ing18', name: 'Salt', quantity: '1 teaspoon', isOnsite: false, isAvailable: true },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'In a bowl, combine breadcrumbs, parmesan, rosemary, thyme, garlic powder, and salt.',
      'Brush chicken breasts with olive oil on all sides.',
      'Press the herb-breadcrumb mixture firmly onto each chicken breast.',
      'Place chicken on a lined baking sheet.',
      'Bake for 25-30 minutes until internal temperature reaches 165°F (74°C).',
      'Let rest for 5 minutes before serving.',
    ],
  },
  {
    id: 3,
    name: 'Berry Smoothie',
    type: 'Beverage',
    description: 'Refreshing smoothie with mixed berries',
    prepTime: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['Quick', 'Healthy', 'Breakfast'],
    hasPriorityIngredients: false,
    onsitePercentage: 90,
    ingredients: [
      {
        id: 'ing19',
        name: 'Blueberries',
        quantity: '1 cup, frozen',
        isOnsite: true,
        isAvailable: true,
      },
      {
        id: 'ing20',
        name: 'Strawberries',
        quantity: '1 cup, frozen',
        isOnsite: true,
        isAvailable: true,
      },
      {
        id: 'ing21',
        name: 'Banana',
        quantity: '1 medium, frozen',
        isOnsite: false,
        isAvailable: true,
      },
      {
        id: 'ing22',
        name: 'Greek Yogurt',
        quantity: '1/2 cup',
        isOnsite: false,
        isAvailable: true,
      },
      { id: 'ing23', name: 'Honey', quantity: '1 tablespoon', isOnsite: true, isAvailable: true },
      { id: 'ing24', name: 'Granola', quantity: '1/4 cup', isOnsite: false, isAvailable: false },
    ],
    instructions: [
      'Add frozen blueberries, strawberries, and banana to a blender.',
      'Add greek yogurt and honey.',
      'Blend until thick and smooth.',
      'Pour into glasses and top with granola.',
      'Serve immediately.',
    ],
  },
];
