export const EVENT_FETCH_REQUEST = 'EVENT_FETCH_REQUEST';
export const EVENT_FETCH_REQUEST_SUCCESS = 'EVENT_FETCH_REQUEST_SUCCESS';
export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';
export const EVENT_CREATE_REQUEST_SUCCESS = 'EVENT_CREATE_REQUEST_SUCCESS';
export const EVENT_REQUEST_FAILURE = 'EVENT_REQUEST_FAILURE';
