export const EVENT_FETCH_REQUEST = 'EVENT_FETCH_REQUEST';
export const EVENT_FETCH_REQUEST_SUCCESS = 'EVENT_FETCH_REQUEST_SUCCESS';
export const EVENT_FETCH_REQUEST_FAILURE = 'EVENT_FETCH_REQUEST_FAILURE';

export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';
export const EVENT_CREATE_REQUEST_SUCCESS = 'EVENT_CREATE_REQUEST_SUCCESS';
export const EVENT_CREATE_REQUEST_FAILURE = 'EVENT_CREATE_REQUEST_FAILURE';

export const CALENDAR_EVENT_FETCH_REQUEST = 'CALENDAR_EVENT_FETCH_REQUEST';
export const CALENDAR_EVENT_FETCH_REQUEST_SUCCESS = 'CALENDAR_EVENT_FETCH_REQUEST_SUCCESS';
export const CALENDAR_EVENT_FETCH_REQUEST_FAILURE = 'CALENDAR_EVENT_FETCH_REQUEST_FAILURE';
