export const GET_NO_SHOWS_DATA = 'GET_NO_SHOWS_DATA';
export const GET_NO_SHOWS_BY_LOCATION = 'GET_NO_SHOWS_BY_LOCATION';
export const GET_NO_SHOWS_BY_AGE_GROUP = 'GET_NO_SHOWS_BY_AGE_GROUP';
export const GET_NO_SHOW_PROPORTIONS = 'GET_NO_SHOW_PROPORTIONS';
export const GET_UNIQUE_EVENT_TYPES = 'GET_UNIQUE_EVENT_TYPES';
export const GET_ATTENDANCE_BY_DAY = 'GET_ATTENDANCE_BY_DAY';
export const SET_ERROR = 'SET_ERROR';
