export const ADD_NEW_SUMMARYGROUP = 'ADD_NEW_SUMMARYGROUP';
export const RECEIVE_ALL_SUMMARY_GROUP = 'RECEIVE_ALL_SUMMARY_GROUP';
export const SUMMARYGROUP_DELETE = 'SUMMARYGROUP_DELETE';
export const UPDATE_SUMMARYGROUP = 'UPDATE_SUMMARYGROUP';
