export const FETCH_USER_TEAMS_START = "FETCH_USER_TEAMS_START";
export const RECEIVE_ALL_USER_TEAMS = "RECIVES_USER_TEAMS";
export const FETCH_USER_TEAMS_ERROR = "FETCH_USER_TEAMS_ERROR";
export const USER_TEAMS_UPDATE = "USER_TEAMS_UPDATE";
export const USER_TEAMS_DELETE = "USER_TEAMS_DELETE";