export const FETCH_USER_TEAMS_START = "FETCH_USER_TEAMS_START";
export const RECEIVE_ALL_USER_TEAMS = "RECIVES_USER_TEAMS";
export const FETCH_USER_TEAMS_ERROR = "FETCH_USER_TEAMS_ERROR";
export const USER_TEAMS_UPDATE = "USER_TEAMS_UPDATE";
export const TEAMS_DELETE = "TEAMS_DELETE";
export const USER_TEAM_CREATION = "USER_TEAM_CREATION";
export const ADD_NEW_TEAM = "ADD_NEW_TEAM";
export const UPDATE_TEAM = "UPDATE_TEAM";