export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_HEADER_DATA = 'SET_HEADER_DATA';
export const START_FORCE_LOGOUT = 'START_FORCE_LOGOUT';
export const STOP_FORCE_LOGOUT = 'STOP_FORCE_LOGOUT';
