export const GET_ALL_BADGE_DATA = 'GET_ALL_BADGE_DATA';
export const ADD_SELECT_BADGE = 'ADD_SELECT_BADGE';
export const REMOVE_SELECT_BADGE = 'REMOVE_SELECT_BADGE';
export const GET_USER_TO_BE_ASSIGNED = 'ET_USER_TO_BE_ASSIGNED';
