export const GET_ALL_BADGE_DATA = 'GET_ALL_BADGE_DATA';
export const ADD_SELECT_BADGE = 'ADD_SELECT_BADGE';
export const REMOVE_SELECT_BADGE = 'REMOVE_SELECT_BADGE';
export const CLEAR_NAME_AND_SELECTED = 'CLEAR_NAME_AND_SELECTED';
export const GET_USER_TO_BE_ASSIGNED = 'GET_USER_TO_BE_ASSIGNED';
export const GET_MESSAGE = 'GET_MESSAGE';
export const CLOSE_ALERT = 'CLOSE_ALERT';
