export const ADD_BLUE_SQUARE_EMAIL_CC = 'ADD_BLUE_SQUARE_EMAIL_CC';
export const REMOVE_BLUE_SQUARE_EMAIL_CC = 'REMOVE_BLUE_SQUARE_EMAIL_CC';
export const BLUE_SQUARE_EMAIL_CC_ERROR = 'BLUE_SQUARE_EMAIL_CC_ERROR';
