// INIT INFOS
export const FETCH_INFOS_START = 'FETCH_INFOS_START';
export const RECEIVE_INFOS = 'RECEIVE_INFOS';
export const FETCH_INFOS_ERROR = 'FETCH_INFOS_ERROR';

// ASSIGN NEW INFOS
export const ADD_NEW_INFO = 'ADD_NEW_INFO';
export const ADD_NEW_INFO_ERROR = 'ADD_NEW_INFO_ERROR';

// UPDATE INFO
export const UPDATE_INFO = 'UPDATE_INFO';
export const UPDATE_INFO_ERROR = 'UPDATE_INFO_ERROR';