// Action type constants for KI Inventory feature

export const KI_INVENTORY_FETCH_REQUEST = 'KI_INVENTORY_FETCH_REQUEST';
export const KI_INVENTORY_FETCH_SUCCESS = 'KI_INVENTORY_FETCH_SUCCESS';
export const KI_INVENTORY_FETCH_FAILURE = 'KI_INVENTORY_FETCH_FAILURE';

export const KI_INVENTORY_STATS_REQUEST = 'KI_INVENTORY_STATS_REQUEST';
export const KI_INVENTORY_STATS_SUCCESS = 'KI_INVENTORY_STATS_SUCCESS';
export const KI_INVENTORY_STATS_FAILURE = 'KI_INVENTORY_STATS_FAILURE';

export const KI_PRESERVED_ITEMS_REQUEST = 'KI_PRESERVED_ITEMS_REQUEST';
export const KI_PRESERVED_ITEMS_SUCCESS = 'KI_PRESERVED_ITEMS_SUCCESS';
export const KI_PRESERVED_ITEMS_FAILURE = 'KI_PRESERVED_ITEMS_FAILURE';
