// Action type constants for KI Inventory feature

export const KI_INVENTORY_FETCH_REQUEST = 'KI_INVENTORY_FETCH_REQUEST';
export const KI_INVENTORY_FETCH_SUCCESS = 'KI_INVENTORY_FETCH_SUCCESS';
export const KI_INVENTORY_FETCH_FAILURE = 'KI_INVENTORY_FETCH_FAILURE';

export const KI_INVENTORY_STATS_REQUEST = 'KI_INVENTORY_STATS_REQUEST';
export const KI_INVENTORY_STATS_SUCCESS = 'KI_INVENTORY_STATS_SUCCESS';
export const KI_INVENTORY_STATS_FAILURE = 'KI_INVENTORY_STATS_FAILURE';

export const KI_PRESERVED_ITEMS_REQUEST = 'KI_PRESERVED_ITEMS_REQUEST';
export const KI_PRESERVED_ITEMS_SUCCESS = 'KI_PRESERVED_ITEMS_SUCCESS';
export const KI_PRESERVED_ITEMS_FAILURE = 'KI_PRESERVED_ITEMS_FAILURE';

export const KI_INVENTORY_ADD_REQUEST = 'KI_INVENTORY_ADD_REQUEST';
export const KI_INVENTORY_ADD_SUCCESS = 'KI_INVENTORY_ADD_SUCCESS';
export const KI_INVENTORY_ADD_FAILURE = 'KI_INVENTORY_ADD_FAILURE';

export const KI_INVENTORY_UPDATE_REQUEST = 'KI_INVENTORY_UPDATE_REQUEST';
export const KI_INVENTORY_UPDATE_SUCCESS = 'KI_INVENTORY_UPDATE_SUCCESS';
export const KI_INVENTORY_UPDATE_FAILURE = 'KI_INVENTORY_UPDATE_FAILURE';

export const KI_INVENTORY_DELETE_REQUEST = 'KI_INVENTORY_DELETE_REQUEST';
export const KI_INVENTORY_DELETE_SUCCESS = 'KI_INVENTORY_DELETE_SUCCESS';
export const KI_INVENTORY_DELETE_FAILURE = 'KI_INVENTORY_DELETE_FAILURE';
