export const FETCH_MEETING_BEGIN = 'FETCH_MEETING_BEGIN';
export const FETCH_MEETING_SUCCESS = 'FETCH_MEETING_SUCCESS';
export const FETCH_MEETING_ERROR = 'FETCH_MEETING_ERROR';

export const FETCH_UNREAD_UPCOMING_MEETING_BEGIN = 'FETCH_UNREAD_UPCOMING_MEETING_BEGIN';
export const FETCH_UNREAD_UPCOMING_MEETING_SUCCESS = 'FETCH_UNREAD_UPCOMING_MEETING_SUCCESS';
export const FETCH_UNREAD_UPCOMING_MEETING_FAILURE = 'FETCH_UNREAD_UPCOMING_MEETING_FAILURE';

export const MARK_MEETING_AS_READ_REQUEST = 'MARK_MEETING_AS_READ_REQUEST';
export const MARK_MEETING_AS_READ_SUCCESS = 'MARK_MEETING_AS_READ_SUCCESS';
export const MARK_MEETING_AS_READ_FAILURE = 'MARK_MEETING_AS_READ_FAILURE';
