export const FETCH_MEETING_BEGIN = 'FETCH_MEETING_BEGIN';
export const FETCH_MEETING_SUCCESS = 'FETCH_MEETING_SUCCESS';
export const FETCH_MEETING_ERROR = 'FETCH_MEETING_ERROR';

export const FETCH_UNREAD_UPCOMING_MEETING_BEGIN = 'FETCH_UNREAD_UPCOMING_MEETING_BEGIN';
export const FETCH_UNREAD_UPCOMING_MEETING_SUCCESS = 'FETCH_UNREAD_UPCOMING_MEETING_SUCCESS';
export const FETCH_UNREAD_UPCOMING_MEETING_FAILURE = 'FETCH_UNREAD_UPCOMING_MEETING_FAILURE';