export const GET_OWNER_STANDARD_MESSAGE = 'GET_OWNER_STANDARD_MESSAGE';
export const CREATE_OWNER_STANDARD_MESSAGE = 'CREATE_OWNER_STANDARD_MESSAGE';
export const UPDATE_OWNER_STANDARD_MESSAGE = 'UPDATE_OWNER_STANDARD_MESSAGE';
export const DELETE_OWNER_STANDARD_MESSAGE = 'DELETE_OWNER_STANDARD_MESSAGE';
