export const GET_OWNER_MESSAGE = 'GET_OWNER_MESSAGE';
export const CREATE_OWNER_MESSAGE = 'CREATE_OWNER_MESSAGE';
export const UPDATE_OWNER_MESSAGE = 'UPDATE_OWNER_MESSAGE';
export const DELETE_OWNER_MESSAGE = 'DELETE_OWNER_MESSAGE';
