// Define your action types here
export const FETCH_PDF_SUMMARY = 'FETCH_PDF_SUMMARY';
export const FETCH_PDF_SUMMARY_SUCCESS = 'FETCH_PDF_SUMMARY_SUCCESS';
export const FETCH_PDF_SUMMARY_FAILURE = 'FETCH_PDF_SUMMARY_FAILURE';
