export const STUDENT_PROFILE_REQUEST = 'STUDENT_PROFILE_REQUEST';
export const STUDENT_PROFILE_SUCCESS = 'STUDENT_PROFILE_SUCCESS';
export const STUDENT_PROFILE_FAIL = 'STUDENT_PROFILE_FAIL';

export const STUDENT_SUBJECT_TASKS_REQUEST = 'STUDENT_SUBJECT_TASKS_REQUEST';
export const STUDENT_SUBJECT_TASKS_SUCCESS = 'STUDENT_SUBJECT_TASKS_SUCCESS';
export const STUDENT_SUBJECT_TASKS_FAIL = 'STUDENT_SUBJECT_TASKS_FAIL';

export const CLEAR_STUDENT_DATA = 'CLEAR_STUDENT_DATA';
