export const GET_SUPPLIER_PERFORMANCE = 'GET_SUPPLIER_PERFORMANCE';
export const GET_PROJECTS = 'GET_PROJECTS';
export const SUPPLIER_PERFORMANCE_ERROR = 'SUPPLIER_PERFORMANCE_ERROR';
export const PROJECTS_ERROR = 'PROJECTS_ERROR';
