export const GET_TIMELOG_TRACKING_START = 'GET_TIMELOG_TRACKING_START';
export const GET_TIMELOG_TRACKING_SUCCESS = 'GET_TIMELOG_TRACKING_SUCCESS';
export const GET_TIMELOG_TRACKING_ERROR = 'GET_TIMELOG_TRACKING_ERROR';
