export const FETCH_TIMEZONE_LOCATION = 'FETCH_TIMEZONE_LOCATION';
export const FETCH_TIMEZONE_LOCATION_ERROR = 'FETCH_TIMEZONE_LOCATION_ERROR';
export const RECEIVE_TIMEZONE_LOCATION = 'RECEIVE_TIMEZONE_LOCATION';
