export const TOOL_REPLCEMENT_REQUEST = 'TOOL_REPLCEMENT_REQUEST';

export const TOOL_REPLACEMENT_SUCCESS = 'TOOL_REPLACEMENT_SUCCESS';

export const TOOL_REPLACEMENT_FAILURE = 'TOOL_REPLACEMENT_FAILURE';
