export const FETCH_TOTAL_ORG_SUMMARY_BEGIN = 'FETCH_TOTAL_ORG_SUMMARY_BEGIN';
export const FETCH_TOTAL_ORG_SUMMARY_SUCCESS = 'FETCH_TOTAL_ORG_SUMMARY_SUCCESS';
export const FETCH_TOTAL_ORG_SUMMARY_ERROR = 'FETCH_TOTAL_ORG_SUMMARY_ERROR';
export const FETCH_TOTAL_ORG_SUMMARY_DATA_SUCCESS = 'FETCH_TOTAL_ORG_SUMMARY_DATA_SUCCESS';
export const FETCH_TOTAL_ORG_SUMMARY_DATA_ERROR = 'FETCH_TOTAL_ORG_SUMMARY_DATA_ERROR';
