export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_TASKS = 'GET_USER_TASKS';
export const GET_USER_PROJECT_BY_ID = 'GET_USER_PROJECT_BY_ID';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const EDIT_FIRST_NAME = 'EDIT_FIRST_NAME';
