export const FETCH_USER_PROFILES_START = 'FETCH_USER_PROFILES_START';
export const RECEIVE_ALL_USER_PROFILES = 'RECIVES_USER_PROFILES';
export const FETCH_USER_PROFILES_ERROR = 'FETCH_USER_PROFILES_ERROR';
export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE';
export const USER_PROFILE_DELETE = 'USER_PROFILE_DELETE';
