export const GET_ALL_USER_PROFILE = 'GET_ALL_USER_PROFILE'
export const FETCH_USER_PROFILES_START = "FETCH_USER_PROFILES_START";
export const RECEIVE_USER_PROFILES = "RECIVES_USER_PROFILES";
export const FETCH_USER_PROFILES_ERROR = "FETCH_USER_PROFILES_ERROR";