export const FETCH_VOLUNTEER_SUMMARIES_REPORT_BEGIN = 'FETCH_SUMMARIES_REPORT_BEGIN';
export const FETCH_VOLUNTEER_SUMMARIES_REPORT_SUCCESS = 'FETCH_SUMMARIES_REPORT_SUCCESS';
export const FETCH_VOLUNTEER_SUMMARIES_REPORT_ERROR = 'FETCH_SUMMARIES_REPORT_ERROR';
