export const FETCH_SUMMARIES_REPORT_BEGIN = 'FETCH_SUMMARIES_REPORT_BEGIN';
export const FETCH_SUMMARIES_REPORT_SUCCESS = 'FETCH_SUMMARIES_REPORT_SUCCESS';
export const FETCH_SUMMARIES_REPORT_ERROR = 'FETCH_SUMMARIES_REPORT_ERROR';
export const UPDATE_SUMMARY_REPORT = 'UPDATE_SUMMARY_REPORT';
