export const FETCH_WEEKLY_SUMMARIES_BEGIN = 'FETCH_WEEKLY_SUMMARIES_BEGIN';
export const FETCH_WEEKLY_SUMMARIES_SUCCESS = 'FETCH_WEEKLY_SUMMARIES_SUCCESS';
export const FETCH_WEEKLY_SUMMARIES_ERROR = 'FETCH_WEEKLY_SUMMARIES_ERROR';
export const POST_WEEKLY_SUMMARY_FILTERS = 'POST_WEEKLY_SUMMARY_FILTERS';
export const GET_USER_WEEKLY_SUMMARY_FILTER = 'GET_USER_WEEKLY_SUMMARY_FILTER';
