// Atom Assignment Constants

export const FETCH_AVAILABLE_ATOMS_START = 'FETCH_AVAILABLE_ATOMS_START';
export const FETCH_AVAILABLE_ATOMS_SUCCESS = 'FETCH_AVAILABLE_ATOMS_SUCCESS';
export const FETCH_AVAILABLE_ATOMS_ERROR = 'FETCH_AVAILABLE_ATOMS_ERROR';

export const ASSIGN_ATOMS_START = 'ASSIGN_ATOMS_START';
export const ASSIGN_ATOMS_SUCCESS = 'ASSIGN_ATOMS_SUCCESS';
export const ASSIGN_ATOMS_ERROR = 'ASSIGN_ATOMS_ERROR';

export const SELECT_ATOM = 'SELECT_ATOM';
export const DESELECT_ATOM = 'DESELECT_ATOM';
export const CLEAR_SELECTIONS = 'CLEAR_SELECTIONS';

export const SET_NOTE = 'SET_NOTE';
export const CLEAR_FORM = 'CLEAR_FORM';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
