export const FETCH_LESSON_PLANS_REQUEST = 'FETCH_LESSON_PLANS_REQUEST';
export const FETCH_LESSON_PLANS_SUCCESS = 'FETCH_LESSON_PLANS_SUCCESS';
export const FETCH_LESSON_PLANS_FAILURE = 'FETCH_LESSON_PLANS_FAILURE';

export const FETCH_LESSON_PLAN_DETAIL_REQUEST = 'FETCH_LESSON_PLAN_DETAIL_REQUEST';
export const FETCH_LESSON_PLAN_DETAIL_SUCCESS = 'FETCH_LESSON_PLAN_DETAIL_SUCCESS';
export const FETCH_LESSON_PLAN_DETAIL_FAILURE = 'FETCH_LESSON_PLAN_DETAIL_FAILURE';

export const SAVE_LESSON_PLAN_REQUEST = 'SAVE_LESSON_PLAN_REQUEST';
export const SAVE_LESSON_PLAN_SUCCESS = 'SAVE_LESSON_PLAN_SUCCESS';
export const SAVE_LESSON_PLAN_FAILURE = 'SAVE_LESSON_PLAN_FAILURE';

export const REMOVE_LESSON_PLAN_REQUEST = 'REMOVE_LESSON_PLAN_REQUEST';
export const REMOVE_LESSON_PLAN_SUCCESS = 'REMOVE_LESSON_PLAN_SUCCESS';
export const REMOVE_LESSON_PLAN_FAILURE = 'REMOVE_LESSON_PLAN_FAILURE';

export const FETCH_SAVED_LESSON_PLANS_REQUEST = 'FETCH_SAVED_LESSON_PLANS_REQUEST';
export const FETCH_SAVED_LESSON_PLANS_SUCCESS = 'FETCH_SAVED_LESSON_PLANS_SUCCESS';
export const FETCH_SAVED_LESSON_PLANS_FAILURE = 'FETCH_SAVED_LESSON_PLANS_FAILURE';

export const CHECK_IF_SAVED_REQUEST = 'CHECK_IF_SAVED_REQUEST';
export const CHECK_IF_SAVED_SUCCESS = 'CHECK_IF_SAVED_SUCCESS';
export const CHECK_IF_SAVED_FAILURE = 'CHECK_IF_SAVED_FAILURE';

export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_VIEW_MODE = 'SET_VIEW_MODE';
