export const FETCH_LESSON_PLANS_REQUEST = 'FETCH_LESSON_PLANS_REQUEST';
export const FETCH_LESSON_PLANS_SUCCESS = 'FETCH_LESSON_PLANS_SUCCESS';
export const FETCH_LESSON_PLANS_FAILURE = 'FETCH_LESSON_PLANS_FAILURE';

export const SAVE_LESSON_PLAN_REQUEST = 'SAVE_LESSON_PLAN_REQUEST';
export const SAVE_LESSON_PLAN_SUCCESS = 'SAVE_LESSON_PLAN_SUCCESS';
export const SAVE_LESSON_PLAN_FAILURE = 'SAVE_LESSON_PLAN_FAILURE';

export const FETCH_SAVED_LESSON_PLANS_REQUEST = 'FETCH_SAVED_LESSON_PLANS_REQUEST';
export const FETCH_SAVED_LESSON_PLANS_SUCCESS = 'FETCH_SAVED_LESSON_PLANS_SUCCESS';
export const FETCH_SAVED_LESSON_PLANS_FAILURE = 'FETCH_SAVED_LESSON_PLANS_FAILURE';
