export const JOB_APPLICATION_GET_FORMS_REQUEST = 'JOB_APPLICATION_GET_FORMS_REQUEST';
export const JOB_APPLICATION_GET_FORMS_SUCCESS = 'JOB_APPLICATION_GET_FORMS_SUCCESS';
export const JOB_APPLICATION_GET_FORMS_FAIL = 'JOB_APPLICATION_GET_FORMS_FAIL';

export const JOB_APPLICATION_SET_SELECTED_JOB = 'JOB_APPLICATION_SET_SELECTED_JOB';
