export const EXPERIENCE_BREAKDOWN_REQUEST = 'EXPERIENCE_BREAKDOWN_REQUEST';
export const EXPERIENCE_BREAKDOWN_SUCCESS = 'EXPERIENCE_BREAKDOWN_SUCCESS';
export const EXPERIENCE_BREAKDOWN_FAILURE = 'EXPERIENCE_BREAKDOWN_FAILURE';
