export const JOBS_APPS_HITS_REQUEST = 'JOBS_APPLICATIONS_HITS_REQUEST';
export const JOBS_APPS_HITS_REQUEST_SUCCESS = 'JOBS_APPLICATIONS_HITS_REQUEST_SUCCESS';
export const JOBS_APPS_HITS_REQUEST_FAILURE = 'JOBS_APPLICATIONS_HITS_REQUEST_FAILURE';
