const sampleMembers = [
  {
    id: 1,
    name: 'Alice Johnson',
    skillScore: 8,
    email: 'alice@example.com',
    emailPrivate: false,
    slackID: 'U1001',
    slackPrivate: false,
  },
  {
    id: 2,
    name: 'Bob Smith',
    skillScore: 3,
    email: '',
    emailPrivate: true,
    slackID: '',
    slackPrivate: true,
  },
  {
    id: 3,
    name: 'Charlie Brown',
    skillScore: 6,
    email: 'charlie@example.com',
    emailPrivate: false,
    slackID: 'U1003',
    slackPrivate: false,
  },
  {
    id: 4,
    name: 'Diana Prince',
    skillScore: 9,
    email: 'diana@example.com',
    emailPrivate: false,
    slackID: 'U1004',
    slackPrivate: false,
  },
  {
    id: 5,
    name: 'Ethan Hunt',
    skillScore: 2,
    email: '',
    emailPrivate: true,
    slackID: 'U1005',
    slackPrivate: false,
  },
  {
    id: 6,
    name: 'Fiona Gallagher',
    skillScore: 7,
    email: 'fiona@example.com',
    emailPrivate: false,
    slackID: '',
    slackPrivate: true,
  },
  {
    id: 7,
    name: 'George Michael',
    skillScore: 5,
    email: 'george@example.com',
    emailPrivate: false,
    slackID: 'U1007',
    slackPrivate: false,
  },
  {
    id: 8,
    name: 'Hannah Montana',
    skillScore: 4,
    email: '',
    emailPrivate: true,
    slackID: '',
    slackPrivate: true,
  },
  {
    id: 9,
    name: 'Ian Malcolm',
    skillScore: 6,
    email: 'ian@example.com',
    emailPrivate: false,
    slackID: 'U1009',
    slackPrivate: false,
  },
  {
    id: 10,
    name: 'Julia Roberts',
    skillScore: 9,
    email: 'julia@example.com',
    emailPrivate: false,
    slackID: '',
    slackPrivate: true,
  },
  {
    id: 11,
    name: 'Kevin Hart',
    skillScore: 3,
    email: 'kevin@example.com',
    emailPrivate: false,
    slackID: 'U1011',
    slackPrivate: false,
  },
  {
    id: 12,
    name: 'Linda Belcher',
    skillScore: 7,
    email: '',
    emailPrivate: true,
    slackID: 'U1012',
    slackPrivate: false,
  },
  {
    id: 13,
    name: 'Michael Scott',
    skillScore: 4,
    email: 'michael@example.com',
    emailPrivate: false,
    slackID: '',
    slackPrivate: true,
  },
  {
    id: 14,
    name: 'Nancy Drew',
    skillScore: 10,
    email: 'nancy@example.com',
    emailPrivate: false,
    slackID: 'U1014',
    slackPrivate: false,
  },
  {
    id: 15,
    name: 'Oscar Isaac',
    skillScore: 5,
    email: 'oscar@example.com',
    emailPrivate: false,
    slackID: 'U1015',
    slackPrivate: false,
  },
  {
    id: 16,
    name: 'Pam Beesly',
    skillScore: 6,
    email: '',
    emailPrivate: true,
    slackID: '',
    slackPrivate: true,
  },
  {
    id: 17,
    name: 'Quincy Adams',
    skillScore: 2,
    email: 'quincy@example.com',
    emailPrivate: false,
    slackID: '',
    slackPrivate: true,
  },
  {
    id: 18,
    name: 'Rachel Green',
    skillScore: 8,
    email: 'rachel@example.com',
    emailPrivate: false,
    slackID: 'U1018',
    slackPrivate: false,
  },
  {
    id: 19,
    name: 'Steve Rogers',
    skillScore: 9,
    email: '',
    emailPrivate: true,
    slackID: 'U1019',
    slackPrivate: false,
  },
  {
    id: 20,
    name: 'Tina Belcher',
    skillScore: 4,
    email: 'tina@example.com',
    emailPrivate: false,
    slackID: '',
    slackPrivate: true,
  },
];

export default sampleMembers;
