export const ENHANCED_POPULARITY_DATA_REQUEST = 'ENHANCED_POPULARITY_DATA_REQUEST';
export const ENHANCED_POPULARITY_DATA_SUCCESS = 'ENHANCED_POPULARITY_DATA_SUCCESS';
export const ENHANCED_POPULARITY_DATA_FAILURE = 'ENHANCED_POPULARITY_DATA_FAILURE';

export const ENHANCED_POPULARITY_ROLES_REQUEST = 'ENHANCED_POPULARITY_ROLES_REQUEST';
export const ENHANCED_POPULARITY_ROLES_SUCCESS = 'ENHANCED_POPULARITY_ROLES_SUCCESS';
export const ENHANCED_POPULARITY_ROLES_FAILURE = 'ENHANCED_POPULARITY_ROLES_FAILURE';
