/**
 * Mock activities data for development and fallback purposes
 * This data is used when:
 * - API is unavailable or fails
 * - Development/testing environment
 * - Demo purposes
 */

export const mockActivities = [
  {
    id: 1,
    name: 'Yoga Class',
    type: 'Fitness',
    date: '2024-01-10',
    time: '10:00 AM',
    description: 'A relaxing yoga session for all levels.',
    location: 'Community Center',
  },
  {
    id: 2,
    name: 'Book Club',
    type: 'Social',
    date: '2024-01-12',
    time: '6:00 PM',
    description: 'Monthly book discussion group.',
    location: 'Library',
  },
  {
    id: 3,
    name: 'Coding Workshop',
    type: 'Educational',
    date: '2023-12-30',
    time: '2:00 PM',
    description: 'Learn the basics of coding in this hands-on workshop.',
    location: 'Tech Hub',
  },
  {
    id: 4,
    name: 'Painting Session',
    type: 'Art',
    date: '2024-01-15',
    time: '4:00 PM',
    description: 'Express your creativity with paints and brushes.',
    location: 'Art Studio',
  },
  {
    id: 5,
    name: 'Dance Class',
    type: 'Fitness',
    date: '2024-01-10',
    time: '7:00 PM',
    description: 'Learn new dance moves and have fun.',
    location: 'Community Center',
  },
  {
    id: 6,
    name: 'Gardening Meetup',
    type: 'Social',
    date: '2024-01-20',
    time: '3:00 PM',
    description: 'Share gardening tips and plant care advice.',
    location: 'Botanical Garden',
  },
  {
    id: 7,
    name: 'Cooking Class',
    type: 'Educational',
    date: '2024-01-18',
    time: '5:00 PM',
    description: 'Learn to cook delicious meals with our expert chefs.',
    location: 'Culinary School',
  },
  {
    id: 8,
    name: 'Photography Walk',
    type: 'Art',
    date: '2023-12-30',
    time: '9:00 AM',
    description: 'Explore the city and capture beautiful moments with your camera.',
    location: 'City Park',
  },
  {
    id: 9,
    name: 'Marathon Training',
    type: 'Fitness',
    date: '2024-02-01',
    time: '6:00 AM',
    description: 'Join us for early morning runs to prepare for the upcoming marathon.',
    location: 'Stadium',
  },
  {
    id: 10,
    name: 'Chess Tournament',
    type: 'Social',
    date: '2024-01-12',
    time: '1:00 PM',
    description: 'Compete in our friendly chess tournament and test your skills.',
    location: 'Library',
  },
  {
    id: 11,
    name: 'Tech Talk',
    type: 'Educational',
    date: '2024-01-15',
    time: '4:00 PM',
    description: 'Join us for an insightful talk on the latest tech trends and innovations.',
    location: 'Tech Hub',
  },
  {
    id: 12,
    name: 'Sculpture Workshop',
    type: 'Art',
    date: '2024-01-25',
    time: '2:00 PM',
    description: 'Learn the art of sculpture and create your own masterpiece.',
    location: 'Art Studio',
  },
  {
    id: 13,
    name: 'Pilates Class',
    type: 'Fitness',
    date: '2024-01-20',
    time: '8:00 AM',
    description: 'Strengthen your core and improve flexibility with our Pilates class.',
    location: 'Community Center',
  },
  {
    id: 14,
    name: 'Film Screening',
    type: 'Social',
    date: '2024-01-18',
    time: '7:00 PM',
    description: 'Join us for a screening of a popular film followed by a discussion.',
    location: 'Library',
  },
  {
    id: 15,
    name: 'Robotics Expo',
    type: 'Educational',
    date: '2024-01-10',
    time: '10:00 AM',
    description: 'Explore the world of robotics with interactive exhibits and demonstrations.',
    location: 'Tech Hub',
  },
  {
    id: 16,
    name: 'Watercolor Workshop',
    type: 'Art',
    date: '2026-01-22',
    time: '3:30 PM',
    description: 'Practice watercolor techniques and create a take-home landscape painting.',
    location: 'Art Studio',
  },
  {
    id: 17,
    name: 'HIIT Workout Class',
    type: 'Fitness',
    date: '2026-02-15',
    time: '6:30 PM',
    description: 'A high-energy interval training session designed to build strength and stamina.',
    location: 'Community Gym',
  },
  {
    id: 18,
    name: 'GenAI for Beginners',
    type: 'Educational',
    date: '2026-09-10',
    time: '5:00 PM',
    description:
      'An introductory session covering practical generative AI tools, prompts, and use cases.',
    location: 'Tech Hub',
  },
  {
    id: 19,
    name: 'Book Club - March',
    type: 'Social',
    date: '2026-10-21',
    time: '6:00 PM',
    description: 'Meet fellow readers for a guided discussion of this month’s featured book.',
    location: 'Library',
  },
];
