const memberRows = [
  ['Alex Brain', 'Organizer', 'Activated', 'Sept. 1, 2024'],
  ['Taylor Smith', 'Participant', 'Joined', 'Aug. 29, 2024'],
  ['Jiaqi Chen', 'Participant', '', 'Aug. 30, 2024'],
  ['Maria Lopez', 'Volunteer', 'Joined', 'Sept. 2, 2024'],
  ['Ethan Garcia', 'Participant', 'Interested', 'Sept. 1, 2024'],
  ['Priya Reddy', 'Participant', 'Joined', 'Sept. 1, 2024'],
  ['Daniel Park', 'Participant', 'Joined', 'Sept. 1, 2024'],
  ['Sarah Johnson', 'Participant', '', 'Sept. 3, 2024'],
  ['Michael Brown', 'Volunteer', 'Joined', 'Sept. 4, 2024'],
  ['Emily Davis', 'Participant', 'Interested', 'Sept. 2, 2024'],
  ['David Wilson', 'Participant', '', 'Aug. 31, 2024'],
  ['Sophia Martinez', 'Volunteer', 'Joined', 'Sept. 5, 2024'],
  ['Liam Anderson', 'Participant', '', 'Sept. 1, 2024'],
  ['Olivia Thomas', 'Participant', 'Joined', 'Sept. 6, 2024'],
  ['Noah Taylor', 'Participant', '', 'Sept. 3, 2024'],
  ['Ava Moore', 'Volunteer', 'Joined', 'Sept. 4, 2024'],
  ['James Lee', 'Participant', 'Interested', 'Sept. 6, 2024'],
  ['Isabella Harris', 'Participant', '', 'Sept. 2, 2024'],
  ['Benjamin Clark', 'Participant', '', 'Sept. 5, 2024'],
  ['Mia Lewis', 'Volunteer', 'Joined', 'Sept. 7, 2024'],
  ['Lucas Walker', 'Participant', '', 'Sept. 3, 2024'],
  ['Amelia Hall', 'Participant', 'Joined', 'Sept. 7, 2024'],
  ['Henry Young', 'Participant', 'Interested', 'Sept. 8, 2024'],
  ['Charlotte King', 'Volunteer', 'Joined', 'Sept. 6, 2024'],
  ['Elijah Scott', 'Participant', '', 'Sept. 4, 2024'],
  ['Harper Green', 'Participant', '', 'Sept. 8, 2024'],
  ['William Baker', 'Participant', 'Joined', 'Sept. 9, 2024'],
  ['Evelyn Adams', 'Volunteer', '', 'Sept. 7, 2024'],
  ['Jack Nelson', 'Participant', 'Interested', 'Sept. 9, 2024'],
  ['Abigail Carter', 'Participant', '', 'Sept. 8, 2024'],
  ['Mateo Ramirez', 'Participant', 'Joined', 'Sept. 10, 2024'],
  ['Ella Rivera', 'Volunteer', '', 'Sept. 10, 2024'],
  ['Logan Perez', 'Participant', '', 'Sept. 6, 2024'],
  ['Grace Collins', 'Participant', 'Joined', 'Sept. 9, 2024'],
  ['Aiden Stewart', 'Participant', '', 'Sept. 11, 2024'],
];

export const members = memberRows.map(([name, role, status, joined]) => ({
  name,
  role,
  status,
  joined,
}));
