export const members = [
  {
    name: 'Alex Brain',
    role: 'Organizer',
    status: 'Activated',
    joined: 'Sept. 1, 2024',
  },
  {
    name: 'Taylor Smith',
    role: 'Participant',
    status: 'Joined',
    joined: 'Aug. 29, 2024',
  },
  {
    name: 'Jiaqi Chen',
    role: 'Participant',
    status: '',
    joined: 'Aug. 30, 2024',
  },
  {
    name: 'Maria Lopez',
    role: 'Volunteer',
    status: 'Joined',
    joined: 'Sept. 2, 2024',
  },
  {
    name: 'Ethan Garcia',
    role: 'Participant',
    status: 'Interested',
    joined: 'Sept. 1, 2024',
  },
  {
    name: 'Priya Reddy',
    role: 'Participant',
    status: 'Joined',
    joined: 'Sept. 1, 2024',
  },
  {
    name: 'Daniel Park',
    role: 'Participant',
    status: 'Joined',
    joined: 'Sept. 1, 2024',
  },
  {
    name: 'Sarah Johnson',
    role: 'Participant',
    status: '',
    joined: 'Sept. 3, 2024',
  },
  {
    name: 'Michael Brown',
    role: 'Volunteer',
    status: 'Joined',
    joined: 'Sept. 4, 2024',
  },
  {
    name: 'Emily Davis',
    role: 'Participant',
    status: 'Interested',
    joined: 'Sept. 2, 2024',
  },
  {
    name: 'David Wilson',
    role: 'Participant',
    status: '',
    joined: 'Aug. 31, 2024',
  },
  {
    name: 'Sophia Martinez',
    role: 'Volunteer',
    status: 'Joined',
    joined: 'Sept. 5, 2024',
  },
  {
    name: 'Liam Anderson',
    role: 'Participant',
    status: '',
    joined: 'Sept. 1, 2024',
  },
  {
    name: 'Olivia Thomas',
    role: 'Participant',
    status: 'Joined',
    joined: 'Sept. 6, 2024',
  },
  {
    name: 'Noah Taylor',
    role: 'Participant',
    status: '',
    joined: 'Sept. 3, 2024',
  },
  {
    name: 'Ava Moore',
    role: 'Volunteer',
    status: 'Joined',
    joined: 'Sept. 4, 2024',
  },
  {
    name: 'James Lee',
    role: 'Participant',
    status: 'Interested',
    joined: 'Sept. 6, 2024',
  },
  {
    name: 'Isabella Harris',
    role: 'Participant',
    status: '',
    joined: 'Sept. 2, 2024',
  },
  {
    name: 'Benjamin Clark',
    role: 'Participant',
    status: '',
    joined: 'Sept. 5, 2024',
  },
  {
    name: 'Mia Lewis',
    role: 'Volunteer',
    status: 'Joined',
    joined: 'Sept. 7, 2024',
  },
  {
    name: 'Lucas Walker',
    role: 'Participant',
    status: '',
    joined: 'Sept. 3, 2024',
  },
  {
    name: 'Amelia Hall',
    role: 'Participant',
    status: 'Joined',
    joined: 'Sept. 7, 2024',
  },
  {
    name: 'Henry Young',
    role: 'Participant',
    status: 'Interested',
    joined: 'Sept. 8, 2024',
  },
  {
    name: 'Charlotte King',
    role: 'Volunteer',
    status: 'Joined',
    joined: 'Sept. 6, 2024',
  },
  {
    name: 'Elijah Scott',
    role: 'Participant',
    status: '',
    joined: 'Sept. 4, 2024',
  },
  {
    name: 'Harper Green',
    role: 'Participant',
    status: '',
    joined: 'Sept. 8, 2024',
  },
  {
    name: 'William Baker',
    role: 'Participant',
    status: 'Joined',
    joined: 'Sept. 9, 2024',
  },
  {
    name: 'Evelyn Adams',
    role: 'Volunteer',
    status: '',
    joined: 'Sept. 7, 2024',
  },
  {
    name: 'Jack Nelson',
    role: 'Participant',
    status: 'Interested',
    joined: 'Sept. 9, 2024',
  },
  {
    name: 'Abigail Carter',
    role: 'Participant',
    status: '',
    joined: 'Sept. 8, 2024',
  },
  {
    name: 'Mateo Ramirez',
    role: 'Participant',
    status: 'Joined',
    joined: 'Sept. 10, 2024',
  },
  {
    name: 'Ella Rivera',
    role: 'Volunteer',
    status: '',
    joined: 'Sept. 10, 2024',
  },
  {
    name: 'Logan Perez',
    role: 'Participant',
    status: '',
    joined: 'Sept. 6, 2024',
  },
  {
    name: 'Grace Collins',
    role: 'Participant',
    status: 'Joined',
    joined: 'Sept. 9, 2024',
  },
  {
    name: 'Aiden Stewart',
    role: 'Participant',
    status: '',
    joined: 'Sept. 11, 2024',
  },
];
