export const MOCK_RESOURCES = [
  {
    id: 1,
    user: 'Alice Johnson',
    timeDuration: '02:32:56',
    facilities: 'Landing Page',
    materials: 'Meadow Lane Oakland',
    date: 'Just now',
    timestamp: Date.now(),
  },
  {
    id: 2,
    user: 'Zane Thompson',
    timeDuration: '01:10:00',
    facilities: 'CRM Admin pages',
    materials: 'Larry San Francisco',
    date: 'A minute ago',
    timestamp: Date.now() - 60000,
  },
  {
    id: 3,
    user: 'Bob Miller',
    timeDuration: '05:20:10',
    facilities: 'Client Project',
    materials: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    timestamp: Date.now() - 3600000,
  },
  {
    id: 4,
    user: 'Charlie Davis',
    timeDuration: '00:45:30',
    facilities: 'Admin Dashboard',
    materials: 'Washburn Baton Rouge',
    date: 'Yesterday',
    timestamp: Date.now() - 86400000,
  },
  {
    id: 5,
    user: 'Diana Prince',
    timeDuration: '03:15:22',
    facilities: 'App Landing page',
    materials: 'Nest Lane Olivette',
    date: 'Feb 2, 2024',
    timestamp: new Date('2024-02-02').getTime(),
  },
  {
    id: 6,
    user: 'Edward Norton',
    timeDuration: '02:32:56',
    facilities: 'Landing Page',
    materials: 'Meadow Lane Oakland',
    date: 'Just now',
    timestamp: Date.now() - 1000,
  },
  {
    id: 7,
    user: 'Fiona Gallagher',
    timeDuration: '02:32:56',
    facilities: 'CRM Admin Pages',
    materials: 'Larry San Francisco',
    date: 'A minute ago',
    timestamp: Date.now() - 61000,
  },
  {
    id: 8,
    user: 'George Clooney',
    timeDuration: '02:32:56',
    facilities: 'Client Project',
    materials: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    timestamp: Date.now() - 3601000,
  },
  {
    id: 9,
    user: 'Hannah Abbott',
    timeDuration: '02:32:56',
    facilities: 'Admin Dashboard',
    materials: 'Washburn Baton Rouge',
    date: 'Yesterday',
    timestamp: Date.now() - 86401000,
  },
  {
    id: 10,
    user: 'Ian Wright',
    timeDuration: '02:32:56',
    facilities: 'App Landing Page',
    materials: 'Nest Lane Olivette',
    date: 'Feb 2, 2024',
    timestamp: new Date('2024-02-02').getTime() - 1000,
  },
  {
    id: 11,
    user: 'Jane Doe',
    timeDuration: '02:32:56',
    facilities: 'Landing Page',
    materials: 'Meadow Lane Oakland',
    date: 'Just now',
    timestamp: Date.now() - 2000,   
  },
  {
    id: 12,
    user: 'John Smith',
    timeDuration: '02:32:56',
    facilities: 'CRM Admin pages',
    materials: 'Larry San Francisco',
    date: 'A minute ago',
    timestamp: Date.now() - 60000,
  },
  {
    id: 13,
    user: 'Emily Davis',
    timeDuration: '02:32:56',
    facilities: 'Client Project',
    materials: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    timestamp: Date.now() - 3600000, 
  },
  {
    id: 14,
    user: 'Michael Brown',
    timeDuration: '02:32:56',
    facilities: 'Admin Dashboard',
    materials: 'Washburn Baton Rouge',
    date: '1 hour ago',
    timestamp: Date.now() - 3600000,
  },
  {
    id: 15,
    user: 'Kevin Hart',
    timeDuration: '01:45:12',
    facilities: 'Landing Page',
    materials: 'Oak Ridge Knoxville',
    date: '2 hours ago',
    timestamp: Date.now() - 7200000,
  },
  {
    id: 16,
    user: 'Laura Palmer',
    timeDuration: '00:20:00',
    facilities: 'CRM Admin pages',
    materials: 'Twin Peaks Snoqualmie',
    date: '3 hours ago',
    timestamp: Date.now() - 10800000,
  },
  {
    id: 17,
    user: 'Miles Morales',
    timeDuration: '04:15:30',
    facilities: 'App Landing page',
    materials: 'Brooklyn Heights NY',
    date: '5 hours ago',
    timestamp: Date.now() - 18000000,
  },
  {
    id: 18,
    user: 'Nancy Wheeler',
    timeDuration: '02:05:45',
    facilities: 'Client Project',
    materials: 'Maple Street Hawkins',
    date: 'Yesterday',
    timestamp: Date.now() - 86400000,
  },
  {
    id: 19,
    user: 'Oscar Isaac',
    timeDuration: '03:50:00',
    facilities: 'Admin Dashboard',
    materials: 'Dune Road Arrakis',
    date: 'Yesterday',
    timestamp: Date.now() - 90000000,
  },
  {
    id: 20,
    user: 'Peter Parker',
    timeDuration: '01:12:00',
    facilities: 'Landing Page',
    materials: 'Queens Blvd Forest Hills',
    date: 'Feb 10, 2024',
    timestamp: new Date('2024-02-10').getTime(),
  },
  {
    id: 21,
    user: 'Quinn Fabray',
    timeDuration: '02:30:15',
    facilities: 'CRM Admin pages',
    materials: 'Lima Ohio Central',
    date: 'Feb 8, 2024',
    timestamp: new Date('2024-02-08').getTime(),
  },
  {
    id: 22,
    user: 'Riley Reid',
    timeDuration: '00:55:40',
    facilities: 'App Landing page',
    materials: 'Sunset Blvd LA',
    date: 'Feb 5, 2024',
    timestamp: new Date('2024-02-05').getTime(),
  },
  {
    id: 23,
    user: 'Sarah Connor',
    timeDuration: '06:00:00',
    facilities: 'Client Project',
    materials: 'SkyNet Lab Tech',
    date: 'Feb 1, 2024',
    timestamp: new Date('2024-02-01').getTime(),
  },
  {
    id: 24,
    user: 'Tony Stark',
    timeDuration: '05:22:10',
    facilities: 'Admin Dashboard',
    materials: 'Malibu Point 10880',
    date: 'Jan 28, 2024',
    timestamp: new Date('2024-01-28').getTime(),
  },
  {
    id: 25,
    user: 'Uma Thurman',
    timeDuration: '03:45:00',
    facilities: 'Landing Page',
    materials: 'Kill Bill Drive LA',
    date: 'Jan 25, 2024',
    timestamp: new Date('2024-01-25').getTime(),
  },
  {
    id: 26,
    user: 'Victor Von Doom',
    timeDuration: '08:00:00',
    facilities: 'Admin Dashboard',
    materials: 'Latveria Castle Grounds',
    date: 'Just now',
    timestamp: Date.now(),
  },
  {
    id: 27,
    user: 'Wanda Maximoff',
    timeDuration: '02:15:00',
    facilities: 'App Landing page',
    materials: 'Westview Suburban Ave',
    date: '5 minutes ago',
    timestamp: Date.now() - 300000,
  },
  {
    id: 28,
    user: 'Xavier Charles',
    timeDuration: '04:20:10',
    facilities: 'Client Project',
    materials: 'Salem Center NY',
    date: '12 minutes ago',
    timestamp: Date.now() - 720000,
  },
  {
    id: 29,
    user: 'Yara Greyjoy',
    timeDuration: '01:45:00',
    facilities: 'CRM Admin pages',
    materials: 'Iron Islands Dock',
    date: '45 minutes ago',
    timestamp: Date.now() - 2700000,
  },
  {
    id: 30,
    user: 'Zelda Hyrule',
    timeDuration: '03:10:05',
    facilities: 'Landing Page',
    materials: 'Great Plateau Way',
    date: '2 hours ago',
    timestamp: Date.now() - 7200000,
  },
  {
    id: 31,
    user: 'Arthur Morgan',
    timeDuration: '06:30:00',
    facilities: 'Client Project',
    materials: 'Blackwater Creek Road',
    date: '4 hours ago',
    timestamp: Date.now() - 14400000,
  },
  {
    id: 32,
    user: 'Bruce Wayne',
    timeDuration: '01:15:00',
    facilities: 'Admin Dashboard',
    materials: 'Wayne Manor Drive',
    date: 'Yesterday',
    timestamp: Date.now() - 86400000,
  },
  {
    id: 33,
    user: 'Clarke Griffin',
    timeDuration: '02:50:30',
    facilities: 'App Landing page',
    materials: 'Arkadia Station',
    date: 'Yesterday',
    timestamp: Date.now() - 90000000,
  },
  {
    id: 34,
    user: 'Din Djarin',
    timeDuration: '00:55:12',
    facilities: 'CRM Admin pages',
    materials: 'Nevarro Trade Plaza',
    date: '2 days ago',
    timestamp: Date.now() - 172800000,
  },
  {
    id: 35,
    user: 'Ellen Ripley',
    timeDuration: '05:00:00',
    facilities: 'Landing Page',
    materials: 'Nostromo Deck B',
    date: 'Jan 20, 2024',
    timestamp: new Date('2024-01-20').getTime(),
  },
  {
    id: 36,
    user: 'Frodo Baggins',
    timeDuration: '09:12:45',
    facilities: 'Client Project',
    materials: 'Bag End Shire',
    date: 'Jan 15, 2024',
    timestamp: new Date('2024-01-15').getTime(),
  },
  {
    id: 37,
    user: 'Geralt of Rivia',
    timeDuration: '03:40:00',
    facilities: 'Admin Dashboard',
    materials: 'Kaer Morhen Keep',
    date: 'Jan 10, 2024',
    timestamp: new Date('2024-01-10').getTime(),
  },
  {
    id: 38,
    user: 'Hal Jordan',
    timeDuration: '01:20:00',
    facilities: 'App Landing page',
    materials: 'Coast City Sector',
    date: 'Jan 05, 2024',
    timestamp: new Date('2024-01-05').getTime(),
  },
  {
    id: 39,
    user: 'Indiana Jones',
    timeDuration: '04:55:00',
    facilities: 'CRM Admin pages',
    materials: 'Marshall College Lib',
    date: 'Jan 01, 2024',
    timestamp: new Date('2024-01-01').getTime(),
  },
  {
    id: 40,
    user: 'Joel Miller',
    timeDuration: '02:10:00',
    facilities: 'Landing Page',
    materials: 'Jackson Hole Wyoming',
    date: 'Dec 28, 2023',
    timestamp: new Date('2023-12-28').getTime(),
  },
  {
    id: 41,
    user: 'Katniss Everdeen',
    timeDuration: '03:22:15',
    facilities: 'Client Project',
    materials: 'District 12 Woods',
    date: 'Dec 25, 2023',
    timestamp: new Date('2023-12-25').getTime(),
  },
  {
    id: 42,
    user: 'Luke Skywalker',
    timeDuration: '00:45:00',
    facilities: 'Admin Dashboard',
    materials: 'Tosche Station Tattooine',
    date: 'Dec 20, 2023',
    timestamp: new Date('2023-12-20').getTime(),
  },
  {
    id: 43,
    user: 'Marty McFly',
    timeDuration: '01:28:00',
    facilities: 'App Landing page',
    materials: 'Hill Valley Square',
    date: 'Dec 15, 2023',
    timestamp: new Date('2023-12-15').getTime(),
  },
  {
    id: 44,
    user: 'Neo Anderson',
    timeDuration: '02:00:00',
    facilities: 'CRM Admin pages',
    materials: 'Nebuchadnezzar Core',
    date: 'Dec 10, 2023',
    timestamp: new Date('2023-12-10').getTime(),
  },
  {
    id: 45,
    user: 'Optimus Prime',
    timeDuration: '07:15:00',
    facilities: 'Landing Page',
    materials: 'Cybertron Central',
    date: 'Dec 05, 2023',
    timestamp: new Date('2023-12-05').getTime(),
  },
  {
    id: 46,
    user: 'Paul Atreides',
    timeDuration: '05:30:00',
    facilities: 'Client Project',
    materials: 'Arrakeen Palace',
    date: 'Dec 01, 2023',
    timestamp: new Date('2023-12-01').getTime(),
  },
  {
    id: 47,
    user: 'Quentin Coldwater',
    timeDuration: '03:10:00',
    facilities: 'Admin Dashboard',
    materials: 'Brakebills University',
    date: 'Nov 28, 2023',
    timestamp: new Date('2023-11-28').getTime(),
  },
  {
    id: 48,
    user: 'Rick Sanchez',
    timeDuration: '00:15:59',
    facilities: 'App Landing page',
    materials: 'Garage Lab C-137',
    date: 'Nov 25, 2023',
    timestamp: new Date('2023-11-25').getTime(),
  },
  {
    id: 49,
    user: 'Steve Rogers',
    timeDuration: '10:00:00',
    facilities: 'CRM Admin pages',
    materials: 'Brooklyn Training Camp',
    date: 'Nov 20, 2023',
    timestamp: new Date('2023-11-20').getTime(),
  },
  {
    id: 50,
    user: 'Thomas Shelby',
    timeDuration: '04:40:20',
    facilities: 'Landing Page',
    materials: 'Small Heath Birmingham',
    date: 'Nov 15, 2023',
    timestamp: new Date('2023-11-15').getTime(),
  }
];
