export const MEMBERS_LIST_REQUEST = 'MEMBERS_LIST_REQUEST';
export const MEMBERS_LIST_REQUEST_SUCCESS = 'MEMBERS_LIST_REQUEST_SUCCESS';
export const MEMBERS_LIST_REQUEST_FAILURE = 'MEMBERS_LIST_REQUEST_FAILURE';
