/**
 * Mock data for community members
 * This simulates data that would come from an API in a real implementation
 * Structure follows the format from the HGNRest/src/controllers/userSkillsProfileController.js
 */
export const mockMembers = [
  {
    userId: '665524c257ca141fe8921b41',
    name: {
      firstName: 'Jatin',
      lastName: 'Agrawal',
      displayName: 'Jatin Agrawal',
    },
    contactInfo: {
      email: 'jatinagrawal0801@gmail.com',
      phone: '+1-555-123-4567',
    },
    jobTitle: ['Software Developer', 'ML Engineer'],
    teams: [
      {
        teamId: 'team1',
        teamName: 'Core Development',
        role: 'Developer',
      },
    ],
    socialHandles: {
      slack: 'Jatin Agrawal',
      github: 'https://github.com/JatinAgrawal94',
    },
    skillInfo: {
      frontend: {
        overall: '1',
        HTML: '3',
        Bootstrap: '3',
        CSS: '3',
        React: '4',
        Redux: '4',
        WebSocketCom: '4',
        ResponsiveUI: '5',
        UnitTest: '5',
        Documentation: '5',
        UIUXTools: '5',
      },
      backend: {
        Overall: '2',
        Database: '4',
        MongoDB: '5',
        MongoDB_Advanced: '5',
        TestDrivenDev: '5',
        Deployment: '5',
        VersionControl: '5',
        CodeReview: '5',
        EnvironmentSetup: '5',
        AdvancedCoding: '5',
        AgileDevelopment: '5',
      },
      general: {
        hours: '10-19',
        period: '>2',
        standup: 'no',
        location: 'Los Angeles, CA, USA',
        manager: 'no',
        combined_frontend_backend: '3',
        mern_skills: '4',
        leadership_skills: '4',
        leadership_experience: '4',
        preferences: ['frontend', 'backend', 'design', 'testing'],
        availability: {
          Monday: '5AM-6AM',
          Tuesday: '6AM-7AM',
          Wednesday: '7AM-8AM',
          Thursday: '8AM-9AM',
          Friday: '9AM-10AM',
        },
      },
      followup: {
        platform: 'windows',
        other_skills: 'machine learning',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['frontend', 'backend', 'design', 'testing'],
      availability: {
        Monday: '5AM-6AM',
        Tuesday: '6AM-7AM',
        Wednesday: '7AM-8AM',
        Thursday: '8AM-9AM',
        Friday: '9AM-10AM',
      },
      leadershipExperience: '4',
      combinedSkills: '3',
    },
    lastUpdated: new Date('2023-08-15T12:30:45'),
    isActive: true,
    isInUserTeam: true,
    profileImage: 'https://via.placeholder.com/150',
  },
  {
    userId: '765524c257ca141fe8921b42',
    name: {
      firstName: 'Shreya',
      lastName: 'Laheri',
      displayName: 'Shreya Laheri',
    },
    contactInfo: {
      email: 'shreya@onecommunity.com',
      phone: '+1-555-987-6543',
    },
    jobTitle: ['Frontend Developer', 'UI/UX Designer'],
    teams: [
      {
        teamId: 'team1',
        teamName: 'Core Development',
        role: 'Lead Designer',
      },
    ],
    socialHandles: {
      slack: 'Shreya Laheri',
      github: 'https://github.com/shreyalaheri',
    },
    skillInfo: {
      frontend: {
        overall: '5',
        HTML: '5',
        Bootstrap: '5',
        CSS: '5',
        React: '5',
        Redux: '4',
        WebSocketCom: '4',
        ResponsiveUI: '5',
        UnitTest: '4',
        Documentation: '5',
        UIUXTools: '5',
      },
      backend: {
        Overall: '3',
        Database: '4',
        MongoDB: '4',
        MongoDB_Advanced: '3',
        TestDrivenDev: '4',
        Deployment: '3',
        VersionControl: '5',
        CodeReview: '5',
        EnvironmentSetup: '4',
        AdvancedCoding: '4',
        AgileDevelopment: '5',
      },
      general: {
        hours: '20-29',
        period: '1-2',
        standup: 'yes',
        location: 'New York, USA',
        manager: 'yes',
        combined_frontend_backend: '5',
        mern_skills: '5',
        leadership_skills: '5',
        leadership_experience: '5',
        preferences: ['frontend', 'design', 'documentation'],
        availability: {
          Monday: '9AM-5PM',
          Wednesday: '9AM-5PM',
          Friday: '9AM-5PM',
        },
      },
      followup: {
        platform: 'mac',
        other_skills: 'project management, team leadership',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['frontend', 'design', 'documentation'],
      availability: {
        Monday: '9AM-5PM',
        Wednesday: '9AM-5PM',
        Friday: '9AM-5PM',
      },
      leadershipExperience: '5',
      combinedSkills: '5',
    },
    lastUpdated: new Date('2023-09-05T10:15:30'),
    isActive: true,
    isInUserTeam: true,
    profileImage: 'https://via.placeholder.com/150',
  },
  {
    userId: '865524c257ca141fe8921b43',
    name: {
      firstName: 'John',
      lastName: 'Doe',
      displayName: 'John Doe',
    },
    contactInfo: {
      email: 'john@onecommunity.com',
      phone: '+1-555-456-7890',
    },
    jobTitle: ['Backend Developer', 'DevOps Engineer'],
    teams: [],
    socialHandles: {
      slack: 'John Doe',
      github: 'https://github.com/johndoe',
    },
    skillInfo: {
      frontend: {
        overall: '3',
        HTML: '4',
        Bootstrap: '3',
        CSS: '3',
        React: '4',
        Redux: '3',
        WebSocketCom: '2',
        ResponsiveUI: '3',
        UnitTest: '4',
        Documentation: '4',
        UIUXTools: '2',
      },
      backend: {
        Overall: '4',
        Database: '5',
        MongoDB: '4',
        MongoDB_Advanced: '4',
        TestDrivenDev: '5',
        Deployment: '5',
        VersionControl: '4',
        CodeReview: '4',
        EnvironmentSetup: '5',
        AdvancedCoding: '4',
        AgileDevelopment: '3',
      },
      general: {
        hours: '20-29',
        period: '0-1',
        standup: 'yes',
        location: 'Seattle, WA, USA',
        manager: 'no',
        combined_frontend_backend: '4',
        mern_skills: '4',
        leadership_skills: '3',
        leadership_experience: '2',
        preferences: ['backend', 'testing', 'deployment'],
        availability: {
          Tuesday: '2PM-6PM',
          Thursday: '2PM-6PM',
          Saturday: '10AM-2PM',
        },
      },
      followup: {
        platform: 'linux',
        other_skills: 'devops, cloud infrastructure',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['backend', 'testing', 'deployment'],
      availability: {
        Tuesday: '2PM-6PM',
        Thursday: '2PM-6PM',
        Saturday: '10AM-2PM',
      },
      leadershipExperience: '2',
      combinedSkills: '4',
    },
    lastUpdated: new Date('2023-10-10T14:45:20'),
    isActive: true,
    isInUserTeam: false,
    profileImage: 'https://via.placeholder.com/150',
  },
  {
    userId: '965524c257ca141fe8921b44',
    name: {
      firstName: 'Maria',
      lastName: 'Garcia',
      displayName: 'Maria Garcia',
    },
    contactInfo: {
      email: 'maria@onecommunity.com',
      phone: '+1-555-222-3333',
    },
    jobTitle: ['UI Designer', 'Graphic Artist'],
    teams: [],
    socialHandles: {
      slack: 'Maria Garcia',
      github: 'https://github.com/mariagarcia',
    },
    skillInfo: {
      frontend: {
        overall: '4',
        HTML: '5',
        Bootstrap: '4',
        CSS: '5',
        React: '3',
        Redux: '2',
        WebSocketCom: '1',
        ResponsiveUI: '5',
        UnitTest: '2',
        Documentation: '4',
        UIUXTools: '5',
      },
      backend: {
        Overall: '1',
        Database: '2',
        MongoDB: '1',
        MongoDB_Advanced: '1',
        TestDrivenDev: '2',
        Deployment: '1',
        VersionControl: '3',
        CodeReview: '2',
        EnvironmentSetup: '2',
        AdvancedCoding: '1',
        AgileDevelopment: '2',
      },
      general: {
        hours: '10-19',
        period: '0-1',
        standup: 'yes',
        location: 'Chicago, IL, USA',
        manager: 'no',
        combined_frontend_backend: '2',
        mern_skills: '2',
        leadership_skills: '2',
        leadership_experience: '1',
        preferences: ['design', 'frontend', 'documentation'],
        availability: {
          Monday: '6PM-9PM',
          Wednesday: '6PM-9PM',
          Friday: '6PM-9PM',
          Sunday: '1PM-5PM',
        },
      },
      followup: {
        platform: 'mac',
        other_skills: 'ui/ux design, graphic design',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['design', 'frontend', 'documentation'],
      availability: {
        Monday: '6PM-9PM',
        Wednesday: '6PM-9PM',
        Friday: '6PM-9PM',
        Sunday: '1PM-5PM',
      },
      leadershipExperience: '1',
      combinedSkills: '2',
    },
    lastUpdated: new Date('2023-07-25T09:20:15'),
    isActive: true,
    isInUserTeam: false,
    profileImage: 'https://via.placeholder.com/150',
  },
  {
    userId: '165524c257ca141fe8921b45',
    name: {
      firstName: 'Alex',
      lastName: 'Smith',
      displayName: 'Alex Smith',
    },
    contactInfo: {
      email: 'alex@onecommunity.com',
      phone: '+1-555-888-9999',
    },
    jobTitle: ['Senior Backend Engineer', 'System Architect'],
    teams: [
      {
        teamId: 'team2',
        teamName: 'Backend Team',
        role: 'Team Lead',
      },
    ],
    socialHandles: {
      slack: 'Alex Smith',
      github: 'https://github.com/alexsmith',
    },
    skillInfo: {
      frontend: {
        overall: '3',
        HTML: '4',
        Bootstrap: '3',
        CSS: '3',
        React: '4',
        Redux: '4',
        WebSocketCom: '3',
        ResponsiveUI: '3',
        UnitTest: '4',
        Documentation: '5',
        UIUXTools: '2',
      },
      backend: {
        Overall: '5',
        Database: '5',
        MongoDB: '5',
        MongoDB_Advanced: '5',
        TestDrivenDev: '5',
        Deployment: '5',
        VersionControl: '5',
        CodeReview: '5',
        EnvironmentSetup: '5',
        AdvancedCoding: '5',
        AgileDevelopment: '5',
      },
      general: {
        hours: '30+',
        period: '>2',
        standup: 'yes',
        location: 'Austin, TX, USA',
        manager: 'yes',
        combined_frontend_backend: '4',
        mern_skills: '5',
        leadership_skills: '5',
        leadership_experience: '5',
        preferences: ['backend', 'testing', 'deployment', 'architecture'],
        availability: {
          Monday: '8AM-5PM',
          Tuesday: '8AM-5PM',
          Wednesday: '8AM-5PM',
          Thursday: '8AM-5PM',
          Friday: '8AM-5PM',
        },
      },
      followup: {
        platform: 'linux',
        other_skills: 'system architecture, security, docker, kubernetes',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['backend', 'testing', 'deployment', 'architecture'],
      availability: {
        Monday: '8AM-5PM',
        Tuesday: '8AM-5PM',
        Wednesday: '8AM-5PM',
        Thursday: '8AM-5PM',
        Friday: '8AM-5PM',
      },
      leadershipExperience: '5',
      combinedSkills: '4',
    },
    lastUpdated: new Date('2023-11-01T16:30:00'),
    isActive: true,
    isInUserTeam: true,
    profileImage: 'https://via.placeholder.com/150',
  },
];
