/**
 * Mock data for community members
 * This simulates data that would come from an API in a real implementation
 * Structure follows the format from the HGNRest/src/controllers/userSkillsProfileController.js
 */
export const mockMembers = [
  {
    userId: '665524c257ca141fe8921b41',
    name: {
      firstName: 'Jatin',
      lastName: 'Agrawal',
      displayName: 'Jatin Agrawal',
    },
    contactInfo: {
      email: 'jatinagrawal0801@gmail.com',
      phone: '+1-555-123-4567',
      public: true,
    },
    jobTitle: ['Software Developer', 'ML Engineer'],
    teams: [
      {
        teamId: 'team1',
        teamName: 'Core Development',
        role: 'Developer',
      },
    ],
    socialHandles: {
      slack: 'Jatin Agrawal',
      github: 'https://github.com/JatinAgrawal94',
    },
    skillInfo: {
      frontend: {
        overall: '2',
        HTML: '6',
        Bootstrap: '6',
        CSS: '6',
        React: '8',
        Redux: '8',
        WebSocketCom: '8',
        ResponsiveUI: '10',
        UnitTest: '10',
        Documentation: '10',
        UIUXTools: '10',
      },
      backend: {
        Overall: '4',
        Database: '8',
        MongoDB: '10',
        MongoDB_Advanced: '10',
        TestDrivenDev: '10',
        Deployment: '10',
        VersionControl: '10',
        CodeReview: '10',
        EnvironmentSetup: '10',
        AdvancedCoding: '10',
        AgileDevelopment: '10',
      },
      general: {
        hours: '10-19',
        period: '>2',
        standup: 'no',
        location: 'Los Angeles, CA, USA',
        manager: 'no',
        combined_frontend_backend: '6',
        mern_skills: '8',
        leadership_skills: '8',
        leadership_experience: '8',
        preferences: ['frontend', 'backend', 'design', 'testing'],
        availability: {
          Monday: '5AM-6AM',
          Tuesday: '6AM-7AM',
          Wednesday: '7AM-8AM',
          Thursday: '8AM-9AM',
          Friday: '9AM-10AM',
        },
      },
      followup: {
        platform: 'windows',
        other_skills: 'machine learning',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['frontend', 'backend', 'design', 'testing'],
      availability: {
        Monday: '5AM-6AM',
        Tuesday: '6AM-7AM',
        Wednesday: '7AM-8AM',
        Thursday: '8AM-9AM',
        Friday: '9AM-10AM',
      },
      leadershipExperience: '8',
      combinedSkills: '6',
    },
    lastUpdated: new Date('2023-08-15T12:30:45'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '765524c257ca141fe8921b42',
    name: {
      firstName: 'Shreya',
      lastName: 'Laheri',
      displayName: 'Shreya Laheri',
    },
    contactInfo: {
      email: null,
      phone: null,
      public: false,
    },
    jobTitle: ['Frontend Developer', 'UI/UX Designer'],
    teams: [
      {
        teamId: 'team1',
        teamName: 'Core Development',
        role: 'Lead Designer',
      },
    ],
    socialHandles: {
      slack: 'Shreya Laheri',
      github: 'https://github.com/shreyalaheri',
    },
    skillInfo: {
      frontend: {
        overall: '10',
        HTML: '10',
        Bootstrap: '10',
        CSS: '10',
        React: '10',
        Redux: '8',
        WebSocketCom: '8',
        ResponsiveUI: '10',
        UnitTest: '8',
        Documentation: '10',
        UIUXTools: '10',
      },
      backend: {
        Overall: '6',
        Database: '8',
        MongoDB: '8',
        MongoDB_Advanced: '6',
        TestDrivenDev: '8',
        Deployment: '6',
        VersionControl: '10',
        CodeReview: '10',
        EnvironmentSetup: '8',
        AdvancedCoding: '8',
        AgileDevelopment: '10',
      },
      general: {
        hours: '20-29',
        period: '1-2',
        standup: 'yes',
        location: 'New York, USA',
        manager: 'yes',
        combined_frontend_backend: '10',
        mern_skills: '10',
        leadership_skills: '10',
        leadership_experience: '10',
        preferences: ['frontend', 'design', 'documentation'],
        availability: {
          Monday: '9AM-5PM',
          Wednesday: '9AM-5PM',
          Friday: '9AM-5PM',
        },
      },
      followup: {
        platform: 'mac',
        other_skills: 'project management, team leadership',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['frontend', 'design', 'documentation'],
      availability: {
        Monday: '9AM-5PM',
        Wednesday: '9AM-5PM',
        Friday: '9AM-5PM',
      },
      leadershipExperience: '10',
      combinedSkills: '10',
    },
    lastUpdated: new Date('2023-09-05T10:15:30'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '865524c257ca141fe8921b43',
    name: {
      firstName: 'John',
      lastName: 'Doe',
      displayName: 'John Doe',
    },
    contactInfo: {
      email: 'john@onecommunity.com',
      phone: '+1-555-456-7890',
      public: true,
    },
    jobTitle: ['Backend Developer', 'DevOps Engineer'],
    teams: [],
    socialHandles: {
      slack: 'John Doe',
      github: 'https://github.com/johndoe',
    },
    skillInfo: {
      frontend: {
        overall: '6',
        HTML: '8',
        Bootstrap: '6',
        CSS: '6',
        React: '8',
        Redux: '6',
        WebSocketCom: '4',
        ResponsiveUI: '6',
        UnitTest: '8',
        Documentation: '8',
        UIUXTools: '4',
      },
      backend: {
        Overall: '8',
        Database: '10',
        MongoDB: '8',
        MongoDB_Advanced: '8',
        TestDrivenDev: '10',
        Deployment: '10',
        VersionControl: '8',
        CodeReview: '8',
        EnvironmentSetup: '10',
        AdvancedCoding: '8',
        AgileDevelopment: '6',
      },
      general: {
        hours: '20-29',
        period: '0-1',
        standup: 'yes',
        location: 'Seattle, WA, USA',
        manager: 'no',
        combined_frontend_backend: '8',
        mern_skills: '8',
        leadership_skills: '6',
        leadership_experience: '4',
        preferences: ['backend', 'testing', 'deployment'],
        availability: {
          Tuesday: '2PM-6PM',
          Thursday: '2PM-6PM',
          Saturday: '10AM-2PM',
        },
      },
      followup: {
        platform: 'linux',
        other_skills: 'devops, cloud infrastructure',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['backend', 'testing', 'deployment'],
      availability: {
        Tuesday: '2PM-6PM',
        Thursday: '2PM-6PM',
        Saturday: '10AM-2PM',
      },
      leadershipExperience: '4',
      combinedSkills: '8',
    },
    lastUpdated: new Date('2023-10-10T14:45:20'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '965524c257ca141fe8921b44',
    name: {
      firstName: 'Maria',
      lastName: 'Garcia',
      displayName: 'Maria Garcia',
    },
    contactInfo: {
      email: 'maria@onecommunity.com',
      phone: '+1-555-222-3333',
      public: true,
    },
    jobTitle: ['UI Designer', 'Graphic Artist'],
    teams: [],
    socialHandles: {
      slack: 'Maria Garcia',
      github: 'https://github.com/mariagarcia',
    },
    skillInfo: {
      frontend: {
        overall: '8',
        HTML: '10',
        Bootstrap: '8',
        CSS: '10',
        React: '6',
        Redux: '4',
        WebSocketCom: '2',
        ResponsiveUI: '10',
        UnitTest: '4',
        Documentation: '8',
        UIUXTools: '10',
      },
      backend: {
        Overall: '2',
        Database: '4',
        MongoDB: '2',
        MongoDB_Advanced: '2',
        TestDrivenDev: '4',
        Deployment: '2',
        VersionControl: '6',
        CodeReview: '4',
        EnvironmentSetup: '4',
        AdvancedCoding: '2',
        AgileDevelopment: '4',
      },
      general: {
        hours: '10-19',
        period: '0-1',
        standup: 'yes',
        location: 'Chicago, IL, USA',
        manager: 'no',
        combined_frontend_backend: '4',
        mern_skills: '4',
        leadership_skills: '4',
        leadership_experience: '2',
        preferences: ['design', 'frontend', 'documentation'],
        availability: {
          Monday: '6PM-9PM',
          Wednesday: '6PM-9PM',
          Friday: '6PM-9PM',
          Sunday: '1PM-5PM',
        },
      },
      followup: {
        platform: 'mac',
        other_skills: 'ui/ux design, graphic design',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['design', 'frontend', 'documentation'],
      availability: {
        Monday: '6PM-9PM',
        Wednesday: '6PM-9PM',
        Friday: '6PM-9PM',
        Sunday: '1PM-5PM',
      },
      leadershipExperience: '2',
      combinedSkills: '4',
    },
    lastUpdated: new Date('2023-07-25T09:20:15'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '165524c257ca141fe8921b45',
    name: {
      firstName: 'Alex',
      lastName: 'Smith',
      displayName: 'Alex Smith',
    },
    contactInfo: {
      email: null,
      phone: null,
      public: false,
    },
    jobTitle: ['Senior Backend Engineer', 'System Architect'],
    teams: [
      {
        teamId: 'team2',
        teamName: 'Backend Team',
        role: 'Team Lead',
      },
    ],
    socialHandles: {
      slack: 'Alex Smith',
      github: 'https://github.com/alexsmith',
    },
    skillInfo: {
      frontend: {
        overall: '6',
        HTML: '8',
        Bootstrap: '6',
        CSS: '6',
        React: '8',
        Redux: '8',
        WebSocketCom: '6',
        ResponsiveUI: '6',
        UnitTest: '8',
        Documentation: '10',
        UIUXTools: '4',
      },
      backend: {
        Overall: '10',
        Database: '10',
        MongoDB: '10',
        MongoDB_Advanced: '10',
        TestDrivenDev: '10',
        Deployment: '10',
        VersionControl: '10',
        CodeReview: '10',
        EnvironmentSetup: '10',
        AdvancedCoding: '10',
        AgileDevelopment: '10',
      },
      general: {
        hours: '30+',
        period: '>2',
        standup: 'yes',
        location: 'Austin, TX, USA',
        manager: 'yes',
        combined_frontend_backend: '8',
        mern_skills: '10',
        leadership_skills: '10',
        leadership_experience: '10',
        preferences: ['backend', 'testing', 'deployment', 'architecture'],
        availability: {
          Monday: '8AM-5PM',
          Tuesday: '8AM-5PM',
          Wednesday: '8AM-5PM',
          Thursday: '8AM-5PM',
          Friday: '8AM-5PM',
        },
      },
      followup: {
        platform: 'linux',
        other_skills: 'system architecture, security, docker, kubernetes',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['backend', 'testing', 'deployment', 'architecture'],
      availability: {
        Monday: '8AM-5PM',
        Tuesday: '8AM-5PM',
        Wednesday: '8AM-5PM',
        Thursday: '8AM-5PM',
        Friday: '8AM-5PM',
      },
      leadershipExperience: '10',
      combinedSkills: '8',
    },
    lastUpdated: new Date('2023-11-01T16:30:00'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '265524c257ca141fe8921b46',
    name: {
      firstName: 'Emily',
      lastName: 'Johnson',
      displayName: 'Emily Johnson',
    },
    contactInfo: {
      email: 'emily@onecommunity.com',
      phone: '+1-555-444-3333',
      public: true,
    },
    jobTitle: ['Full Stack Developer', 'Scrum Master'],
    teams: [
      {
        teamId: 'team3',
        teamName: 'Agile Team',
        role: 'Scrum Master',
      },
    ],
    socialHandles: {
      slack: 'Emily Johnson',
      github: 'https://github.com/emilyjohnson',
    },
    skillInfo: {
      frontend: {
        overall: '8',
        HTML: '10',
        Bootstrap: '8',
        CSS: '8',
        React: '10',
        Redux: '8',
        WebSocketCom: '6',
        ResponsiveUI: '8',
        UnitTest: '10',
        Documentation: '10',
        UIUXTools: '6',
      },
      backend: {
        Overall: '8',
        Database: '8',
        MongoDB: '8',
        MongoDB_Advanced: '6',
        TestDrivenDev: '10',
        Deployment: '8',
        VersionControl: '10',
        CodeReview: '10',
        EnvironmentSetup: '8',
        AdvancedCoding: '8',
        AgileDevelopment: '10',
      },
      general: {
        hours: '20-29',
        period: '>2',
        standup: 'yes',
        location: 'Portland, OR, USA',
        manager: 'yes',
        combined_frontend_backend: '8',
        mern_skills: '8',
        leadership_skills: '10',
        leadership_experience: '10',
        preferences: ['frontend', 'backend', 'project management'],
        availability: {
          Monday: '7AM-3PM',
          Tuesday: '7AM-3PM',
          Wednesday: '7AM-3PM',
          Thursday: '7AM-3PM',
          Friday: '7AM-12PM',
        },
      },
      followup: {
        platform: 'mac',
        other_skills: 'agile methodologies, scrum, project management',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['frontend', 'backend', 'project management'],
      availability: {
        Monday: '7AM-3PM',
        Tuesday: '7AM-3PM',
        Wednesday: '7AM-3PM',
        Thursday: '7AM-3PM',
        Friday: '7AM-12PM',
      },
      leadershipExperience: '10',
      combinedSkills: '8',
    },
    lastUpdated: new Date('2023-10-20T11:25:30'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '365524c257ca141fe8921b47',
    name: {
      firstName: 'Michael',
      lastName: 'Chen',
      displayName: 'Michael Chen',
    },
    contactInfo: {
      email: 'michael@onecommunity.com',
      phone: '+1-555-777-8888',
      public: true,
    },
    jobTitle: ['Data Scientist', 'ML Engineer'],
    teams: [
      {
        teamId: 'team4',
        teamName: 'Data Science Team',
        role: 'Data Scientist',
      },
    ],
    socialHandles: {
      slack: 'Michael Chen',
      github: 'https://github.com/michaelchen',
    },
    skillInfo: {
      frontend: {
        overall: '4',
        HTML: '6',
        Bootstrap: '4',
        CSS: '4',
        React: '6',
        Redux: '4',
        WebSocketCom: '2',
        ResponsiveUI: '4',
        UnitTest: '6',
        Documentation: '8',
        UIUXTools: '2',
      },
      backend: {
        Overall: '8',
        Database: '10',
        MongoDB: '8',
        MongoDB_Advanced: '8',
        TestDrivenDev: '8',
        Deployment: '6',
        VersionControl: '8',
        CodeReview: '8',
        EnvironmentSetup: '6',
        AdvancedCoding: '10',
        AgileDevelopment: '6',
      },
      general: {
        hours: '20-29',
        period: '1-2',
        standup: 'yes',
        location: 'San Francisco, CA, USA',
        manager: 'no',
        combined_frontend_backend: '6',
        mern_skills: '6',
        leadership_skills: '6',
        leadership_experience: '4',
        preferences: ['data science', 'backend', 'research'],
        availability: {
          Monday: '10AM-6PM',
          Wednesday: '10AM-6PM',
          Friday: '10AM-6PM',
        },
      },
      followup: {
        platform: 'linux',
        other_skills: 'machine learning, python, data analysis, tensorflow',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['data science', 'backend', 'research'],
      availability: {
        Monday: '10AM-6PM',
        Wednesday: '10AM-6PM',
        Friday: '10AM-6PM',
      },
      leadershipExperience: '4',
      combinedSkills: '6',
    },
    lastUpdated: new Date('2023-09-15T13:40:10'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '465524c257ca141fe8921b48',
    name: {
      firstName: 'Sarah',
      lastName: 'Williams',
      displayName: 'Sarah Williams',
    },
    contactInfo: {
      email: null,
      phone: null,
      public: false,
    },
    jobTitle: ['Content Manager', 'Technical Writer'],
    teams: [
      {
        teamId: 'team5',
        teamName: 'Documentation Team',
        role: 'Lead Writer',
      },
    ],
    socialHandles: {
      slack: 'Sarah Williams',
      github: 'https://github.com/sarahwilliams',
    },
    skillInfo: {
      frontend: {
        overall: '4',
        HTML: '8',
        Bootstrap: '6',
        CSS: '6',
        React: '4',
        Redux: '2',
        WebSocketCom: '2',
        ResponsiveUI: '4',
        UnitTest: '2',
        Documentation: '10',
        UIUXTools: '6',
      },
      backend: {
        Overall: '2',
        Database: '4',
        MongoDB: '2',
        MongoDB_Advanced: '2',
        TestDrivenDev: '2',
        Deployment: '2',
        VersionControl: '6',
        CodeReview: '4',
        EnvironmentSetup: '2',
        AdvancedCoding: '2',
        AgileDevelopment: '6',
      },
      general: {
        hours: '10-19',
        period: '1-2',
        standup: 'yes',
        location: 'Denver, CO, USA',
        manager: 'no',
        combined_frontend_backend: '2',
        mern_skills: '2',
        leadership_skills: '6',
        leadership_experience: '6',
        preferences: ['documentation', 'content', 'design'],
        availability: {
          Tuesday: '9AM-3PM',
          Thursday: '9AM-3PM',
          Friday: '9AM-3PM',
        },
      },
      followup: {
        platform: 'windows',
        other_skills: 'content management, technical writing, editing',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['documentation', 'content', 'design'],
      availability: {
        Tuesday: '9AM-3PM',
        Thursday: '9AM-3PM',
        Friday: '9AM-3PM',
      },
      leadershipExperience: '6',
      combinedSkills: '2',
    },
    lastUpdated: new Date('2023-08-05T10:15:45'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '565524c257ca141fe8921b49',
    name: {
      firstName: 'David',
      lastName: 'Kim',
      displayName: 'David Kim',
    },
    contactInfo: {
      email: 'david@onecommunity.com',
      phone: '+1-555-333-4444',
      public: true,
    },
    jobTitle: ['Mobile Developer', 'React Native Specialist'],
    teams: [
      {
        teamId: 'team6',
        teamName: 'Mobile Team',
        role: 'Developer',
      },
    ],
    socialHandles: {
      slack: 'David Kim',
      github: 'https://github.com/davidkim',
    },
    skillInfo: {
      frontend: {
        overall: '8',
        HTML: '8',
        Bootstrap: '6',
        CSS: '8',
        React: '10',
        Redux: '10',
        WebSocketCom: '6',
        ResponsiveUI: '10',
        UnitTest: '8',
        Documentation: '6',
        UIUXTools: '8',
      },
      backend: {
        Overall: '6',
        Database: '6',
        MongoDB: '6',
        MongoDB_Advanced: '4',
        TestDrivenDev: '8',
        Deployment: '6',
        VersionControl: '8',
        CodeReview: '8',
        EnvironmentSetup: '6',
        AdvancedCoding: '8',
        AgileDevelopment: '6',
      },
      general: {
        hours: '20-29',
        period: '1-2',
        standup: 'yes',
        location: 'Boston, MA, USA',
        manager: 'no',
        combined_frontend_backend: '8',
        mern_skills: '8',
        leadership_skills: '6',
        leadership_experience: '4',
        preferences: ['mobile', 'frontend', 'react native'],
        availability: {
          Monday: '11AM-7PM',
          Tuesday: '11AM-7PM',
          Thursday: '11AM-7PM',
          Friday: '11AM-7PM',
        },
      },
      followup: {
        platform: 'mac',
        other_skills: 'react native, mobile development, app publishing',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['mobile', 'frontend', 'react native'],
      availability: {
        Monday: '11AM-7PM',
        Tuesday: '11AM-7PM',
        Thursday: '11AM-7PM',
        Friday: '11AM-7PM',
      },
      leadershipExperience: '4',
      combinedSkills: '8',
    },
    lastUpdated: new Date('2023-10-25T14:20:30'),
    isActive: true,
    profileImage: null,
  },
  {
    userId: '665524c257ca141fe8921b50',
    name: {
      firstName: 'Olivia',
      lastName: 'Martinez',
      displayName: 'Olivia Martinez',
    },
    contactInfo: {
      email: 'olivia@onecommunity.com',
      phone: '+1-555-666-7777',
      public: true,
    },
    jobTitle: ['QA Engineer', 'Test Automation Specialist'],
    teams: [
      {
        teamId: 'team7',
        teamName: 'QA Team',
        role: 'Lead QA',
      },
    ],
    socialHandles: {
      slack: 'Olivia Martinez',
      github: 'https://github.com/oliviamartinez',
    },
    skillInfo: {
      frontend: {
        overall: '6',
        HTML: '8',
        Bootstrap: '6',
        CSS: '6',
        React: '6',
        Redux: '4',
        WebSocketCom: '4',
        ResponsiveUI: '6',
        UnitTest: '10',
        Documentation: '10',
        UIUXTools: '6',
      },
      backend: {
        Overall: '6',
        Database: '8',
        MongoDB: '6',
        MongoDB_Advanced: '4',
        TestDrivenDev: '10',
        Deployment: '8',
        VersionControl: '8',
        CodeReview: '10',
        EnvironmentSetup: '8',
        AdvancedCoding: '6',
        AgileDevelopment: '8',
      },
      general: {
        hours: '30+',
        period: '>2',
        standup: 'yes',
        location: 'Miami, FL, USA',
        manager: 'yes',
        combined_frontend_backend: '6',
        mern_skills: '6',
        leadership_skills: '8',
        leadership_experience: '8',
        preferences: ['testing', 'automation', 'quality assurance'],
        availability: {
          Monday: '8AM-4PM',
          Tuesday: '8AM-4PM',
          Wednesday: '8AM-4PM',
          Thursday: '8AM-4PM',
          Friday: '8AM-4PM',
        },
      },
      followup: {
        platform: 'windows',
        other_skills: 'test automation, selenium, cypress, quality assurance',
        suggestion: 'no',
        additional_info: 'no',
      },
      preferences: ['testing', 'automation', 'quality assurance'],
      availability: {
        Monday: '8AM-4PM',
        Tuesday: '8AM-4PM',
        Wednesday: '8AM-4PM',
        Thursday: '8AM-4PM',
        Friday: '8AM-4PM',
      },
      leadershipExperience: '8',
      combinedSkills: '6',
    },
    lastUpdated: new Date('2023-11-10T09:30:15'),
    isActive: true,
    profileImage: null,
  },
];
